In [24]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

1. get the cleaned ministery data

In [44]:
df_ministere = pd.read_csv("../../results/Soil/myministereData.csv")
df_ministere = df_ministere.drop(columns=["Unnamed: 0"])
df_ministere.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   194 non-null    float64
 1   Y                   194 non-null    float64
 2   altitude            194 non-null    float64
 3   UD                  194 non-null    int64
 4   LD                  194 non-null    int64
 5   average profondeur  194 non-null    float64
 6   USDA Soil Taxonomy  0 non-null      float64
 7   pH                  160 non-null    float64
 8   CE                  154 non-null    float64
 9   CEC                 0 non-null      float64
 10  A%                  193 non-null    float64
 11  L%                  192 non-null    float64
 12  S%                  193 non-null    float64
 13  ALR(L)              0 non-null      float64
 14  ALR(S)              0 non-null      float64
 15  OM                  152 non-null    float64
dtypes: float64(14), int64(2)
memory usage: 24.4 KB

2. get the cleaned PDF and given data Combined

In [45]:
df_pdf = pd.read_csv("../../results/Soil/CombinedData.csv")
df_pdf = df_pdf.drop(columns=["Unnamed: 0.1" , "Unnamed: 0"])
df_pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2819 entries, 0 to 2818
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   2738 non-null   float64
 1   Y                   2746 non-null   float64
 2   altitude            1710 non-null   object
 3   UD                  2744 non-null   float64
 4   LD                  2689 non-null   float64
 5   average profondeur  2558 non-null   float64
 6   USDA Soil Taxonomy  824 non-null    object
 7   pH                  2533 non-null   float64
 8   CE                  2440 non-null   float64
 9   CEC                 1745 non-null   float64
 10  A%                  2357 non-null   float64
 11  L%                  2353 non-null   float64
 12  S%                  2370 non-null   float64
 13  ALR(L)              1239 non-null   float64
 14  ALR(S)              1183 non-null   float64
 15  OM                  2108 non-null   float64
dtypes: float64(14), object(2)
memory usage: 352.5+ KB

In [48]:
df = pd.concat([df_pdf , df_ministere])
df = df.drop(columns=["altitude" , "USDA Soil Taxonomy"])
df = df.dropna(subset=["X" , "Y"])
df

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.10700,36.684000,15.0,30.0,22.5,7.870,0.170,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
1,3.10700,36.684000,30.0,60.0,45.0,7.774,0.170,17.207000,40.361496,37.281777,22.356727,-0.034471,-0.256559,1.503000
2,3.10700,36.684000,60.0,100.0,80.0,7.799,0.170,15.049000,49.608530,42.317043,8.074427,-0.069041,-0.788445,0.706000
3,3.13333,36.071667,15.0,30.0,22.5,7.950,0.260,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
4,3.13333,36.071667,30.0,60.0,45.0,8.096,0.279,40.610953,33.898341,39.248386,26.853273,0.063643,-0.101181,1.097000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,1.33000,36.220000,30.0,60.0,45.0,NaN,NaN,NaN,2.818182,1.090909,2.363636,NaN,NaN,0.109091
190,1.33000,36.220000,30.0,60.0,45.0,NaN,NaN,NaN,23.351351,7.297297,15.324324,NaN,NaN,NaN
191,1.33000,36.220000,60.0,100.0,80.0,NaN,NaN,NaN,8.648649,2.702703,5.675676,NaN,NaN,NaN
192,1.33000,36.220000,60.0,100.0,80.0,NaN,NaN,NaN,30.000000,6.000000,13.333333,NaN,NaN,NaN
193,1.33000,36.220000,100.0,200.0,150.0,NaN,NaN,NaN,15.000000,3.000000,6.666667,NaN,NaN,NaN

3. Treating the missing values

In [50]:
numeric_df = df.select_dtypes(include=['float64', 'int64'])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

imputer = KNNImputer(n_neighbors=5)
imputed_array = imputer.fit_transform(scaled_data)
real_values = scaler.inverse_transform(imputed_array)
df[numeric_df.columns] = real_values
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2905 entries, 0 to 193
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   2905 non-null   float64
 1   Y                   2905 non-null   float64
 2   UD                  2905 non-null   float64
 3   LD                  2905 non-null   float64
 4   average profondeur  2905 non-null   float64
 5   pH                  2905 non-null   float64
 6   CE                  2905 non-null   float64
 7   CEC                 2905 non-null   float64
 8   A%                  2905 non-null   float64
 9   L%                  2905 non-null   float64
 10  S%                  2905 non-null   float64
 11  ALR(L)              2905 non-null   float64
 12  ALR(S)              2905 non-null   float64
 13  OM                  2905 non-null   float64
dtypes: float64(14)
memory usage: 340.4 KB

4. Saving the dataset

In [53]:
df.to_csv("../../results/Soil/final_Soil_dataset.csv")

In [54]:
df.drop_duplicates(subset=["X","Y"])

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.107000,36.684000,15.0,30.0,22.5,7.870000,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
3,3.133330,36.071667,15.0,30.0,22.5,7.950000,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
5,3.150000,36.724167,15.0,30.0,22.5,8.500000,2.632808,40.610953,13.000000,32.000000,55.000000,0.391206,0.626419,7.270000
7,2.880278,36.757500,5.0,15.0,10.0,8.590000,0.370000,40.610953,7.210000,11.570000,81.220000,0.205397,1.051727,4.100000
9,3.178361,36.704083,15.0,30.0,22.5,7.830000,2.632808,3.750000,27.239966,42.857252,29.902781,13.704000,0.674285,1.360000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,1.300000,36.210000,0.0,5.0,2.5,0.916667,0.053571,1.362000,3.690476,1.190476,2.023810,55.012000,17.992000,0.095238
159,1.340000,36.200000,0.0,5.0,2.5,0.816327,0.051020,1.362000,3.469388,2.244898,0.612245,55.012000,17.992000,0.091837
168,1.330000,36.210000,0.0,5.0,2.5,1.114286,0.100000,1.362000,4.142857,1.857143,3.000000,55.012000,17.992000,0.171429
177,1.330000,36.200000,0.0,5.0,2.5,1.076872,4.726000,1.362000,4.428571,1.714286,3.714286,55.012000,17.992000,0.171429
186,1.330000,36.220000,0.0,5.0,2.5,1.076872,4.726000,1.362000,4.696970,1.818182,3.939394,55.012000,17.992000,0.181818

5. generate Inputs/outputs : outputs saved to v5