In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os 
import rasterio
from rasterio.transform import rowcol
from rasterio.transform import xy
from rasterio.windows import Window

# Data Explanation : 
1. Fauna : all animals distribution (amphibians , birds , mammals , reptiles) the data gives th nombre of birds , mammals ...etc in this area for example each pixel containe 1km²and the value is he number of animals in this area (form 0 --> 153  or 0 --> 178)

2. vegetation : the percentage of a specific land cover  (barren , evergreen, herbaceous) in speicific area (pixel)

3. human activities : gives the human modification in 1km² area between 0 and 1 

we can deduct somethings like : 
- High Species Richness + Low Human Modification → Biodiversity hotspots with low disturbance (ideal for conservation).
- High Species Richness + High Human Modification → Threatened ecosystems (urgent conservation priority).
- Low Species Richness + High Human Modification → Urban/agricultural areas with low ecological value.
- Low Species Richness + Low Human Modification → Natural areas with fewer species (e.g., deserts).

In [25]:
df = pd.read_csv("../results/Soil/final_Soil_dataset.csv")
df

,Unnamed: 0,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,0,3.10700,36.684000,15.0,30.0,22.5,7.870000,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
1,1,3.10700,36.684000,30.0,60.0,45.0,7.774000,0.170000,17.207000,40.361496,37.281777,22.356727,-0.034471,-0.256559,1.503000
2,2,3.10700,36.684000,60.0,100.0,80.0,7.799000,0.170000,15.049000,49.608530,42.317043,8.074427,-0.069041,-0.788445,0.706000
3,3,3.13333,36.071667,15.0,30.0,22.5,7.950000,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
4,4,3.13333,36.071667,30.0,60.0,45.0,8.096000,0.279000,40.610953,33.898341,39.248386,26.853273,0.063643,-0.101181,1.097000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2746,189,1.33000,36.220000,30.0,60.0,45.0,2.178122,4.704309,1.362000,2.818182,1.090909,2.363636,34.166000,17.992000,0.109091
2747,190,1.33000,36.220000,30.0,60.0,45.0,7.946000,3.350000,1.362000,23.351351,7.297297,15.324324,42.366000,23.120000,3.284000
2748,191,1.33000,36.220000,60.0,100.0,80.0,7.822000,3.350000,1.528000,8.648649,2.702703,5.675676,35.140000,23.120000,3.808000
2749,192,1.33000,36.220000,60.0,100.0,80.0,7.822000,3.350000,1.486000,30.000000,6.000000,13.333333,35.140000,23.120000,3.808000
2750,193,1.33000,36.220000,100.0,200.0,150.0,7.996000,3.350000,1.528000,15.000000,3.000000,6.666667,31.216000,23.120000,3.254000

In [26]:
df = df.drop(columns=["Unnamed: 0"])
df

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.10700,36.684000,15.0,30.0,22.5,7.870000,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
1,3.10700,36.684000,30.0,60.0,45.0,7.774000,0.170000,17.207000,40.361496,37.281777,22.356727,-0.034471,-0.256559,1.503000
2,3.10700,36.684000,60.0,100.0,80.0,7.799000,0.170000,15.049000,49.608530,42.317043,8.074427,-0.069041,-0.788445,0.706000
3,3.13333,36.071667,15.0,30.0,22.5,7.950000,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
4,3.13333,36.071667,30.0,60.0,45.0,8.096000,0.279000,40.610953,33.898341,39.248386,26.853273,0.063643,-0.101181,1.097000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2746,1.33000,36.220000,30.0,60.0,45.0,2.178122,4.704309,1.362000,2.818182,1.090909,2.363636,34.166000,17.992000,0.109091
2747,1.33000,36.220000,30.0,60.0,45.0,7.946000,3.350000,1.362000,23.351351,7.297297,15.324324,42.366000,23.120000,3.284000
2748,1.33000,36.220000,60.0,100.0,80.0,7.822000,3.350000,1.528000,8.648649,2.702703,5.675676,35.140000,23.120000,3.808000
2749,1.33000,36.220000,60.0,100.0,80.0,7.822000,3.350000,1.486000,30.000000,6.000000,13.333333,35.140000,23.120000,3.808000
2750,1.33000,36.220000,100.0,200.0,150.0,7.996000,3.350000,1.528000,15.000000,3.000000,6.666667,31.216000,23.120000,3.254000

In [27]:
df_unique = df.copy()
df_unique = df_unique.drop_duplicates(subset=["X" ,"Y"])
df_unique

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.107000,36.684000,15.0,30.0,22.5,7.870000,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
3,3.133330,36.071667,15.0,30.0,22.5,7.950000,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
5,3.150000,36.724167,15.0,30.0,22.5,8.500000,2.632808,40.610953,13.000000,32.000000,55.000000,0.391206,0.626419,7.270000
7,2.880278,36.757500,5.0,15.0,10.0,8.590000,0.370000,40.610953,7.210000,11.570000,81.220000,0.205397,1.051727,4.100000
9,3.178361,36.704083,15.0,30.0,22.5,7.830000,2.632808,3.750000,27.239966,42.857252,29.902781,13.704000,0.674285,1.360000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,1.300000,36.210000,0.0,5.0,2.5,0.916667,0.053571,1.362000,3.690476,1.190476,2.023810,55.012000,17.992000,0.095238
2716,1.340000,36.200000,0.0,5.0,2.5,0.816327,0.051020,1.362000,3.469388,2.244898,0.612245,55.012000,17.992000,0.091837
2725,1.330000,36.210000,0.0,5.0,2.5,1.114286,0.100000,1.362000,4.142857,1.857143,3.000000,55.012000,17.992000,0.171429
2734,1.330000,36.200000,0.0,5.0,2.5,1.076872,4.726000,1.362000,4.428571,1.714286,3.714286,55.012000,17.992000,0.171429
2743,1.330000,36.220000,0.0,5.0,2.5,1.076872,4.726000,1.362000,4.696970,1.818182,3.939394,55.012000,17.992000,0.181818

In [44]:
def latlon_to_pixel(lon, lat, dataset ,transform):
    # Validate if the coordinate is within the image bounds
    if not (dataset.bounds.left <= lon <= dataset.bounds.right and
            dataset.bounds.bottom <= lat <= dataset.bounds.top):
            print(dataset.bounds.left , lon , dataset.bounds.right)
            print(dataset.bounds.bottom , lat , dataset.bounds.top)
    # Convert to pixel row & column
    row, col = rowcol(dataset.transform, lon, lat)
    return row, col

In [29]:
# windows Forming  for full one file (nefthou el file mera brk)
def window_forming(raster_path, df, height=7, width=7 , var=None):
    covariable_files = os.listdir(raster_path)
    covariable_num = len(covariable_files)

    datasets = [rasterio.open(os.path.join(raster_path, fname)) for fname in covariable_files]
    transforms = [ds.transform for ds in datasets]

    windows = []
    mid = height // 2

    for i in range(len(df)):
        print(f"Processing point {i}")
        lat = df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]
        window = np.empty((height, width, covariable_num))

        for idx, src in enumerate(datasets):
            transform = transforms[idx]
            if var :
                pixel_y, pixel_x = latlon_to_pixel(lon, lat, src, transform)
            else : 
                pixel_y, pixel_x = latlon_to_pixel(lat, lon, src, transform)

            try:
                win = Window(pixel_x - mid, pixel_y - mid, width, height)
                data = src.read(1, window=win)
                window[:, :, idx] = data

            except Exception as e:
                print(f"Error at point {i}, covariable {idx}")
                print(e)
                window[:, :, idx] = np.nan  # Fill with NaNs on failure

        windows.append(window)

    for ds in datasets:
        ds.close()

    return windows

In [30]:
# for devided tiff files 
def window_forming2(raster_path  , df ,height=7 , width=7 ):
    covariable_num = len(os.listdir(raster_path))
    windows = []

    for i in range(len(df)) :

        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]

        window = np.empty((height, width, covariable_num))
        for index , j in enumerate(os.listdir(raster_path)):
            with rasterio.open(f"{raster_path}/{j}") as src :
                raster_data = src.read()
                transform = src.transform 
                
            try : 
                pixel_x ,pixel_y = latlon_to_pixel(lat , lon , src , transform)
                mid = height//2
                window[:,:,index] = raster_data[ 0 , pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
                break 
            except Exception as e:
                print("can'found in ")
                continue 
        
        windows.append(window)
    return windows

In [31]:
def window_forming3(all_files  , df ,height=7 , width=7 ):
    covariable_num = len(all_files)
    windows = []
    for i in range(len(df)) :
        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]

        window = np.empty((height, width, covariable_num))

        for index , i in enumerate(all_files):
            raster_data = i.raster_data
            pixel_x ,pixel_y = latlon_to_pixel(lat , lon ,  i.src , i.transform)
            print(pixel_x , pixel_y)
            mid = height//2
            try : 
                window[:,:,index] = raster_data[ pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
            except Exception as e:
                print("error is here ")
                print(e)
        windows.append(window)
    return windows

### 1.Climat

In [32]:
climat_window = window_forming("../Resmapled/climat/" , df_unique)
climat_window = np.array(climat_window)
np.save("../Data_multi_CNN/climat.npy", climat_window)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
Processing point 448
Processing point 449
Processing point 450
Processing point 451
Processing point 452
Processing point 453
Processing point 454
Processing point 455
Processing point 456
Processing point 457
Processing point 458
Processing point 459
Processing point 460
Processing point 461
Processing point 462
Processing point 463
Processing point 464
Processing point 465
Processing point 466
Processing point 467
Processing point 468
Processing point 469
Processing point 470
Processing point 471
Processing point 472
Processing point 473
Processing point 474
Processing point 475
Processing point 476
Processing point 477
Processing point 478
Processing point 479
Processing point 480
Processing point 481
Processing point 482
Processing point 483
Processing point 484
Processing point 485
Processing point 486
Processing point 487
Processing point 488
Processing point 489
Processing point 490
Processing point 491
Processing point 492
Processing point 493
Processing point 494
Processing point 495

In [33]:
climat_window.shape

(496, 7, 7, 6)

### 2. organisme

In [34]:
organisme = window_forming("../Resmapled/organisme/" , df_unique)
organisme = np.array(organisme)
print(organisme.shape)
np.save("../Data_multi_CNN/organisme.npy", organisme)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
Processing point 448
Processing point 449
Processing point 450
Processing point 451
Processing point 452
Processing point 453
Processing point 454
Processing point 455
Processing point 456
Processing point 457
Processing point 458
Processing point 459
Processing point 460
Processing point 461
Processing point 462
Processing point 463
Processing point 464
Processing point 465
Processing point 466
Processing point 467
Processing point 468
Processing point 469
Processing point 470
Processing point 471
Processing point 472
Processing point 473
Processing point 474
Processing point 475
Processing point 476
Processing point 477
Processing point 478
Processing point 479
Processing point 480
Processing point 481
Processing point 482
Processing point 483
Processing point 484
Processing point 485
Processing point 486
Processing point 487
Processing point 488
Processing point 489
Processing point 490
Processing point 491
Processing point 492
Processing point 493
Processing point 494
Processing point 495
(496, 7, 7, 18)

### 3. relief

In [35]:
relief = window_forming("../Resmapled/relief/" , df_unique)
relief = np.array(relief)
print(relief.shape)
np.save("../Data_multi_CNN/relief.npy", relief)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
Processing point 448
Processing point 449
Processing point 450
Processing point 451
Processing point 452
Processing point 453
Processing point 454
Processing point 455
Processing point 456
Processing point 457
Processing point 458
Processing point 459
Processing point 460
Processing point 461
Processing point 462
Processing point 463
Processing point 464
Processing point 465
Processing point 466
Processing point 467
Processing point 468
Processing point 469
Processing point 470
Processing point 471
Processing point 472
Processing point 473
Processing point 474
Processing point 475
Processing point 476
Processing point 477
Processing point 478
Processing point 479
Processing point 480
Processing point 481
Processing point 482
Processing point 483
Processing point 484
Processing point 485
Processing point 486
Processing point 487
Processing point 488
Processing point 489
Processing point 490
Processing point 491
Processing point 492
Processing point 493
Processing point 494
Processing point 495
(496, 7, 7, 7)

### 4. Spatial Position

In [ ]:
landuse_window = window_forming2("../Resmapled/saptialPosition/landuse/" , df_unique)
water_window = window_forming2("../Resmapled/saptialPosition/water/" , df_unique)
np.save("../Data_multi_CNN/landuse.npy", landuse_window)
np.save("../Data_multi_CNN/water.npy", water_window)

the dataset is in : 0
the dataset is in : 1
the dataset is in : 2
the dataset is in : 3
the dataset is in : 4
the dataset is in : 5
the dataset is in : 6
the dataset is in : 7
34.999583333333334 34.72694444 39.999583333333334
-0.0004166666666662877 6.273938889 4.999583333333334
the dataset is in : 8
34.999583333333334 34.71834444 39.999583333333334
-0.0004166666666662877 6.306361111000001 4.999583333333334
the dataset is in : 9
34.999583333333334 34.63508056 39.999583333333334
-0.0004166666666662877 5.101466667000004 4.999583333333334
the dataset is in : 10
34.999583333333334 34.63802222 39.999583333333334
-0.0004166666666662877 5.137791667000002 4.999583333333334
the dataset is in : 11
34.999583333333334 34.71680833 39.999583333333334
-0.0004166666666662877 5.369911111 4.999583333333334
the dataset is in : 12
34.999583333333334 34.72976111 39.999583333333334
-0.0004166666666662877 5.389869443999999 4.999583333333334
the dataset is in : 13
34.999583333333334 34.8095 39.999583333333334
-0.0004166666666662877 5.685094444000001 4.999583333333334
the dataset is in : 14
34.999583333333334 34.80611111 39.999583333333334
-0.0004166666666662877 5.721369443999997 4.999583333333334
the dataset is in : 15
34.999583333333334 34.70161111 39.999583333333334
-0.0004166666666662877 6.425194443999999 4.999583333333334
the dataset is in : 16
34.999583333333334 34.695475 39.999583333333334
-0.0004166666666662877 6.454083333 4.999583333333334
the dataset is in : 17
34.999583333333334 34.90718611 39.999583333333334
-0.0004166666666662877 5.632847222000002 4.999583333333334
the dataset is in : 18
34.999583333333334 34.92097222 39.999583333333334
-0.0004166666666662877 5.616736111000002 4.999583333333334
the dataset is in : 19
34.999583333333334 35.71345833 39.999583333333334
-0.0004166666666662877 6.346855556000001 4.999583333333334
the dataset is in : 20
34.999583333333334 35.61777778 39.999583333333334
-0.0004166666666662877 6.247500000000002 4.999583333333334
the dataset is in : 21
34.999583333333334 35.60833333 39.999583333333334
-0.0004166666666662877 6.231924999999997 4.999583333333334
the dataset is in : 22
34.999583333333334 35.58756389 39.999583333333334
-0.0004166666666662877 6.208108332999998 4.999583333333334
the dataset is in : 23
34.999583333333334 35.60268333 39.999583333333334
-0.0004166666666662877 6.224972221999998 4.999583333333334
the dataset is in : 24
34.999583333333334 35.61046389 39.999583333333334
-0.0004166666666662877 6.238977777999999 4.999583333333334
the dataset is in : 25
34.999583333333334 35.60833056 39.999583333333334
-0.0004166666666662877 6.252397221999999 4.999583333333334
the dataset is in : 26
34.999583333333334 35.61090833 39.999583333333334
-0.0004166666666662877 6.262180555999997 4.999583333333334
the dataset is in : 27
34.999583333333334 35.614025 39.999583333333334
-0.0004166666666662877 6.282777778000003 4.999583333333334
the dataset is in : 28
34.999583333333334 35.61632222 39.999583333333334
-0.0004166666666662877 6.272188888999999 4.999583333333334
the dataset is in : 29
34.999583333333334 35.60964444 39.999583333333334
-0.0004166666666662877 6.270536110999998 4.999583333333334
the dataset is in : 30
the dataset is in : 31
the dataset is in : 32
the dataset is in : 33
the dataset is in : 34
the dataset is in : 35
the dataset is in : 36
the dataset is in : 37
the dataset is in : 38
the dataset is in : 39
the dataset is in : 40
the dataset is in : 41
the dataset is in : 42
the dataset is in : 43
the dataset is in : 44
34.999583333333334 36.8693603 39.999583333333334
-0.0004166666666662877 6.085000000000001 4.999583333333334
the dataset is in : 45
34.999583333333334 36.76858333 39.999583333333334
-0.0004166666666662877 5.7913055559999975 4.999583333333334
the dataset is in : 46
34.999583333333334 36.81563889 39.999583333333334
-0.0004166666666662877 5.916888888999999 4.999583333333334
the dataset is in : 47
34.999583333333334 36.87777778 39.999583333333334
-0.0004166666666662877 6.149777778000001 4.999583333333334
the dataset is in : 48
34.999583333333334 36.80644919 39.999583333333334
-0.0004166666666662877 5.816666667 4.999583333333334
the dataset is in : 49
34.999583333333334 36.78841667 39.999583333333334
-0.0004166666666662877 5.896416666999997 4.999583333333334
the dataset is in : 50
34.999583333333334 36.8076079 39.999583333333334
-0.0004166666666662877 5.783333333000002 4.999583333333334
the dataset is in : 51
34.999583333333334 36.80333333 39.999583333333334
-0.0004166666666662877 5.945277777999998 4.999583333333334
the dataset is in : 52
34.999583333333334 36.8075 39.999583333333334
-0.0004166666666662877 5.942222221999998 4.999583333333334
the dataset is in : 53
34.999583333333334 36.805 39.999583333333334
-0.0004166666666662877 5.942777778 4.999583333333334
the dataset is in : 54
34.999583333333334 36.83416667 39.999583333333334
-0.0004166666666662877 5.983441749999997 4.999583333333334
the dataset is in : 55
34.999583333333334 36.83416667 39.999583333333334
-0.0004166666666662877 5.983055556000004 4.999583333333334
the dataset is in : 56
34.999583333333334 36.71055556 39.999583333333334
-0.0004166666666662877 5.550277778000002 4.999583333333334
the dataset is in : 57
34.999583333333334 36.70916667 39.999583333333334
-0.0004166666666662877 5.548055556000001 4.999583333333334
the dataset is in : 58
34.999583333333334 36.70805556 39.999583333333334
-0.0004166666666662877 5.548055556000001 4.999583333333334
the dataset is in : 59
34.999583333333334 36.70777778 39.999583333333334
-0.0004166666666662877 5.549999999999997 4.999583333333334
the dataset is in : 60
34.999583333333334 36.7425 39.999583333333334
-0.0004166666666662877 6.399166667000003 4.999583333333334
the dataset is in : 61
34.999583333333334 36.74166667 39.999583333333334
-0.0004166666666662877 6.399444444000004 4.999583333333334
the dataset is in : 62
34.999583333333334 36.74194444 39.999583333333334
-0.0004166666666662877 6.398611111000001 4.999583333333334
the dataset is in : 63
the dataset is in : 64
the dataset is in : 65
the dataset is in : 66
the dataset is in : 67
the dataset is in : 68
the dataset is in : 69
the dataset is in : 70
the dataset is in : 71
the dataset is in : 72
the dataset is in : 73
the dataset is in : 74
the dataset is in : 75
the dataset is in : 76
the dataset is in : 77
the dataset is in : 78
the dataset is in : 79
the dataset is in : 80
the dataset is in : 81
the dataset is in : 82
the dataset is in : 83
the dataset is in : 84
the dataset is in : 85
the dataset is in : 86
the dataset is in : 87
the dataset is in : 88
the dataset is in : 89
the dataset is in : 90
the dataset is in : 91
the dataset is in : 92
the dataset is in : 93
the dataset is in : 94
the dataset is in : 95
the dataset is in : 96
the dataset is in : 97
the dataset is in : 98
the dataset is in : 99
the dataset is in : 100
the dataset is in : 101
the dataset is in : 102
the dataset is in : 103
the dataset is in : 104
the dataset is in : 105
the dataset is in : 106
the dataset is in : 107
the dataset is in : 108
the dataset is in : 109
the dataset is in : 110
the dataset is in : 111
the dataset is in : 112
the dataset is in : 113
the dataset is in : 114
the dataset is in : 115
the dataset is in : 116
the dataset is in : 117
the dataset is in : 118
the dataset is in : 119
the dataset is in : 120
the dataset is in : 121
the dataset is in : 122
the dataset is in : 123
the dataset is in : 124
the dataset is in : 125
the dataset is in : 126
the dataset is in : 127
the dataset is in : 128
the dataset is in : 129
34.999583333333334 35.56102417 39.999583333333334
-0.0004166666666662877 6.173911388999997 4.999583333333334
the dataset is in : 130
the dataset is in : 131
the dataset is in : 132
the dataset is in : 133
34.999583333333334 36.15978667 39.999583333333334
-0.0004166666666662877 5.417518889 4.999583333333334
the dataset is in : 134
34.999583333333334 36.78194444 39.999583333333334
-0.0004166666666662877 7.803333332999998 4.999583333333334
the dataset is in : 135
34.999583333333334 36.78083333 39.999583333333334
-0.0004166666666662877 7.803055555999997 4.999583333333334
the dataset is in : 136
34.999583333333334 36.78194444 39.999583333333334
-0.0004166666666662877 7.804722222000002 4.999583333333334
the dataset is in : 137
34.999583333333334 36.78083333 39.999583333333334
-0.0004166666666662877 7.804444443999998 4.999583333333334
the dataset is in : 138
34.999583333333334 36.78166667 39.999583333333334
-0.0004166666666662877 7.805833333000002 4.999583333333334
the dataset is in : 139
34.999583333333334 36.78055556 39.999583333333334
-0.0004166666666662877 7.805555556000002 4.999583333333334
the dataset is in : 140
34.999583333333334 36.78138889 39.999583333333334
-0.0004166666666662877 7.808055555999999 4.999583333333334
the dataset is in : 141
34.999583333333334 36.78027778 39.999583333333334
-0.0004166666666662877 7.807777778000002 4.999583333333334
the dataset is in : 142
34.999583333333334 36.78055556 39.999583333333334
-0.0004166666666662877 7.809722221999998 4.999583333333334
the dataset is in : 143
34.999583333333334 36.78166667 39.999583333333334
-0.0004166666666662877 7.691944444000001 4.999583333333334
the dataset is in : 144
34.999583333333334 36.78194444 39.999583333333334
-0.0004166666666662877 7.694166666999997 4.999583333333334
the dataset is in : 145
34.999583333333334 36.78305556 39.999583333333334
-0.0004166666666662877 7.695555556000002 4.999583333333334
the dataset is in : 146
34.999583333333334 36.78111111 39.999583333333334
-0.0004166666666662877 7.698333333000001 4.999583333333334
the dataset is in : 147
34.999583333333334 36.84861111 39.999583333333334
-0.0004166666666662877 7.9925 4.999583333333334
the dataset is in : 148
34.999583333333334 36.9 39.999583333333334
-0.0004166666666662877 8.199999999999996 4.999583333333334
the dataset is in : 149
34.999583333333334 36.90472222 39.999583333333334
-0.0004166666666662877 8.341388889000001 4.999583333333334
the dataset is in : 150
34.999583333333334 36.84388889 39.999583333333334
-0.0004166666666662877 8.174722222 4.999583333333334
the dataset is in : 151
34.999583333333334 36.0775 39.999583333333334
-0.0004166666666662877 5.324166667 4.999583333333334
the dataset is in : 152
34.999583333333334 36.07472222 39.999583333333334
-0.0004166666666662877 5.307222222 4.999583333333334
the dataset is in : 153
34.999583333333334 35.94583333 39.999583333333334
-0.0004166666666662877 5.280000000000001 4.999583333333334
the dataset is in : 154
34.999583333333334 36.06583333 39.999583333333334
-0.0004166666666662877 5.335000000000001 4.999583333333334
the dataset is in : 155
34.999583333333334 36.125 39.999583333333334
-0.0004166666666662877 5.346666667000001 4.999583333333334
the dataset is in : 156
34.999583333333334 36.13333333 39.999583333333334
-0.0004166666666662877 5.333333332999999 4.999583333333334
the dataset is in : 157
34.999583333333334 36.15 39.999583333333334
-0.0004166666666662877 5.350000000000001 4.999583333333334
the dataset is in : 158
34.999583333333334 36.07583333 39.999583333333334
-0.0004166666666662877 5.296666667000004 4.999583333333334
the dataset is in : 159
34.999583333333334 36.07527778 39.999583333333334
-0.0004166666666662877 5.296666667000004 4.999583333333334
the dataset is in : 160
34.999583333333334 36.07416667 39.999583333333334
-0.0004166666666662877 5.295277777999999 4.999583333333334
the dataset is in : 161
34.999583333333334 36.07444444 39.999583333333334
-0.0004166666666662877 5.295000000000002 4.999583333333334
the dataset is in : 162
the dataset is in : 163
34.999583333333334 36.85083333 39.999583333333334
-0.0004166666666662877 6.879444444000001 4.999583333333334
the dataset is in : 164
34.999583333333334 36.84805556 39.999583333333334
-0.0004166666666662877 6.8852777780000025 4.999583333333334
the dataset is in : 165
34.999583333333334 36.8475 39.999583333333334
-0.0004166666666662877 6.896111111000003 4.999583333333334
the dataset is in : 166
34.999583333333334 36.84666667 39.999583333333334
-0.0004166666666662877 6.899166667000003 4.999583333333334
the dataset is in : 167
34.999583333333334 36.84833333 39.999583333333334
-0.0004166666666662877 6.879166667 4.999583333333334
the dataset is in : 168
34.999583333333334 36.85055556 39.999583333333334
-0.0004166666666662877 6.883333333000003 4.999583333333334
the dataset is in : 169
34.999583333333334 36.8625 39.999583333333334
-0.0004166666666662877 6.889444443999999 4.999583333333334
the dataset is in : 170
34.999583333333334 36.86333333 39.999583333333334
-0.0004166666666662877 6.892499999999998 4.999583333333334
the dataset is in : 171
34.999583333333334 36.86055556 39.999583333333334
-0.0004166666666662877 6.893333333000001 4.999583333333334
the dataset is in : 172
34.999583333333334 36.84833333 39.999583333333334
-0.0004166666666662877 6.899166667000003 4.999583333333334
the dataset is in : 173
34.999583333333334 36.84888889 39.999583333333334
-0.0004166666666662877 6.899999999999999 4.999583333333334
the dataset is in : 174
34.999583333333334 36.84666667 39.999583333333334
-0.0004166666666662877 6.899999999999999 4.999583333333334
the dataset is in : 175
34.999583333333334 36.84722222 39.999583333333334
-0.0004166666666662877 6.903888889000001 4.999583333333334
the dataset is in : 176
34.999583333333334 36.84722222 39.999583333333334
-0.0004166666666662877 6.904722221999997 4.999583333333334
the dataset is in : 177
the dataset is in : 178
the dataset is in : 179
the dataset is in : 180
34.999583333333334 35.56 39.999583333333334
-0.0004166666666662877 6.170000000000002 4.999583333333334
the dataset is in : 181
34.999583333333334 32.49 39.999583333333334
-0.0004166666666662877 3.6700000000000017 4.999583333333334
the dataset is in : 182
the dataset is in : 183
the dataset is in : 184
34.999583333333334 52.39 39.999583333333334
-0.0004166666666662877 2.93 4.999583333333334
can'found in
39.999583333333334 52.39 44.999583333333334
-0.0004166666666662877 2.93 4.999583333333334
can'found in
34.999583333333334 52.39 39.999583333333334
4.999583333333334 2.93 9.999583333333334
can'found in
39.999583333333334 52.39 44.999583333333334
4.999583333333334 2.93 9.999583333333334
can'found in
the dataset is in : 185
34.999583333333334 36.16 39.999583333333334
-0.0004166666666662877 5.420000000000002 4.999583333333334
the dataset is in : 186
34.999583333333334 30.43 39.999583333333334
-0.0004166666666662877 2.140000000000001 4.999583333333334
the dataset is in : 187
the dataset is in : 188
34.999583333333334 34.72 39.999583333333334
-0.0004166666666662877 6.280000000000001 4.999583333333334
the dataset is in : 189
34.999583333333334 34.72 39.999583333333334
-0.0004166666666662877 6.299999999999997 4.999583333333334
the dataset is in : 190
34.999583333333334 34.63 39.999583333333334
-0.0004166666666662877 5.130000000000003 4.999583333333334
the dataset is in : 191
34.999583333333334 34.72 39.999583333333334
-0.0004166666666662877 5.369999999999997 4.999583333333334
the dataset is in : 192
34.999583333333334 34.8 39.999583333333334
-0.0004166666666662877 5.68 4.999583333333334
the dataset is in : 193
34.999583333333334 34.8 39.999583333333334
-0.0004166666666662877 5.719999999999999 4.999583333333334
the dataset is in : 194
34.999583333333334 34.7 39.999583333333334
-0.0004166666666662877 6.43 4.999583333333334
the dataset is in : 195
34.999583333333334 34.68 39.999583333333334
-0.0004166666666662877 6.450000000000003 4.999583333333334
the dataset is in : 196
34.999583333333334 34.9 39.999583333333334
-0.0004166666666662877 5.630000000000003 4.999583333333334
the dataset is in : 197
34.999583333333334 34.92 39.999583333333334
-0.0004166666666662877 5.630000000000003 4.999583333333334
the dataset is in : 198
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 6.109999999999999 4.999583333333334
the dataset is in : 199
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 6.100000000000001 4.999583333333334
the dataset is in : 200
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 6.119999999999997 4.999583333333334
the dataset is in : 201
34.999583333333334 35.57 39.999583333333334
-0.0004166666666662877 6.109999999999999 4.999583333333334
the dataset is in : 202
34.999583333333334 35.56 39.999583333333334
-0.0004166666666662877 5.950000000000003 4.999583333333334
the dataset is in : 203
34.999583333333334 35.57 39.999583333333334
-0.0004166666666662877 5.960000000000001 4.999583333333334
the dataset is in : 204
34.999583333333334 35.57 39.999583333333334
-0.0004166666666662877 5.950000000000003 4.999583333333334
the dataset is in : 205
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 5.950000000000003 4.999583333333334
the dataset is in : 206
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 5.939999999999998 4.999583333333334
the dataset is in : 207
34.999583333333334 35.59 39.999583333333334
-0.0004166666666662877 5.960000000000001 4.999583333333334
the dataset is in : 208
34.999583333333334 35.59 39.999583333333334
-0.0004166666666662877 5.969999999999999 4.999583333333334
the dataset is in : 209
34.999583333333334 35.62 39.999583333333334
-0.0004166666666662877 6.229999999999997 4.999583333333334
the dataset is in : 210
34.999583333333334 35.63 39.999583333333334
-0.0004166666666662877 6.240000000000002 4.999583333333334
the dataset is in : 211
34.999583333333334 35.6 39.999583333333334
-0.0004166666666662877 6.25 4.999583333333334
the dataset is in : 212
34.999583333333334 35.59 39.999583333333334
-0.0004166666666662877 6.210000000000001 4.999583333333334
the dataset is in : 213
34.999583333333334 35.6 39.999583333333334
-0.0004166666666662877 6.219999999999999 4.999583333333334
the dataset is in : 214
34.999583333333334 35.6 39.999583333333334
-0.0004166666666662877 6.229999999999997 4.999583333333334
the dataset is in : 215
34.999583333333334 35.61 39.999583333333334
-0.0004166666666662877 6.240000000000002 4.999583333333334
the dataset is in : 216
34.999583333333334 35.61 39.999583333333334
-0.0004166666666662877 6.25 4.999583333333334
the dataset is in : 217
34.999583333333334 35.61 39.999583333333334
-0.0004166666666662877 6.270000000000003 4.999583333333334
the dataset is in : 218
34.999583333333334 35.58 39.999583333333334
-0.0004166666666662877 6.189999999999998 4.999583333333334
the dataset is in : 219
34.999583333333334 35.59 39.999583333333334
-0.0004166666666662877 6.109999999999999 4.999583333333334
the dataset is in : 220
34.999583333333334 35.63 39.999583333333334
-0.0004166666666662877 6.039999999999999 4.999583333333334
the dataset is in : 221
34.999583333333334 35.63 39.999583333333334
-0.0004166666666662877 6.189999999999998 4.999583333333334
the dataset is in : 222
34.999583333333334 35.62 39.999583333333334
-0.0004166666666662877 6.170000000000002 4.999583333333334
the dataset is in : 223
34.999583333333334 35.53 39.999583333333334
-0.0004166666666662877 5.880000000000003 4.999583333333334
the dataset is in : 224
the dataset is in : 225
the dataset is in : 226
the dataset is in : 227
the dataset is in : 228
34.999583333333334 12.0 39.999583333333334
-0.0004166666666662877 1.0 4.999583333333334
can'found in
39.999583333333334 12.0 44.999583333333334
-0.0004166666666662877 1.0 4.999583333333334
can'found in
34.999583333333334 12.0 39.999583333333334
4.999583333333334 1.0 9.999583333333334
can'found in
39.999583333333334 12.0 44.999583333333334
4.999583333333334 1.0 9.999583333333334
can'found in
the dataset is in : 229
34.999583333333334 32.87 39.999583333333334
-0.0004166666666662877 0.5300000000000011 4.999583333333334
the dataset is in : 230
34.999583333333334 36.85 39.999583333333334
-0.0004166666666662877 7.960000000000001 4.999583333333334
the dataset is in : 231
34.999583333333334 36.93 39.999583333333334
-0.0004166666666662877 8.119999999999997 4.999583333333334
the dataset is in : 232
34.999583333333334 36.95 39.999583333333334

In [40]:
np.array(landuse_window).shape

(496, 7, 7, 1)

In [41]:
np.array(water_window).shape

(496, 7, 7, 4)

### 4. Parent Material

In [45]:
parent_window = window_forming("../Resmapled/ParentMaterial/", df_unique)
np.save("../Data_multi_CNN/Parent_Material.npy", parent_window)
np.array(parent_window).shape

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
-8.67386818000005 2.93 11.988910679999922
18.960031509999993 52.39 37.08087101632086
Error at point 184, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
-22.4133525492225 2.93 64.54036521609329
-38.574875710885514 52.39 40.0038669850103
Error at point 184, covariable 1
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
-8.67386818000005 1.0 11.988910679999922
18.960031509999993 12.0 37.08087101632086
Error at point 228, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
-8.67386818000005 0.75 11.988910679999922
18.960031509999993 37.88 37.08087101632086
Error at point 254, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 255
-8.67386818000005 0.6700000000000017 11.988910679999922
18.960031509999993 37.85 37.08087101632086
Error at point 255, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 256
-8.67386818000005 0.75 11.988910679999922
18.960031509999993 37.92 37.08087101632086
Error at point 256, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 257
-8.67386818000005 0.740000000000002 11.988910679999922
18.960031509999993 37.92 37.08087101632086
Error at point 257, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 258
-8.67386818000005 0.6300000000000026 11.988910679999922
18.960031509999993 37.87 37.08087101632086
Error at point 258, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 259
-8.67386818000005 0.740000000000002 11.988910679999922
18.960031509999993 37.88 37.08087101632086
Error at point 259, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 260
-8.67386818000005 0.7199999999999989 11.988910679999922
18.960031509999993 37.89 37.08087101632086
Error at point 260, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 261
-8.67386818000005 0.7899999999999991 11.988910679999922
18.960031509999993 37.96 37.08087101632086
Error at point 261, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 262
-8.67386818000005 0.740000000000002 11.988910679999922
18.960031509999993 37.91 37.08087101632086
Error at point 262, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 263
-8.67386818000005 0.7700000000000031 11.988910679999922
18.960031509999993 37.97 37.08087101632086
Error at point 263, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 264
-8.67386818000005 0.759999999999998 11.988910679999922
18.960031509999993 37.88 37.08087101632086
Error at point 264, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 265
-8.67386818000005 0.6599999999999966 11.988910679999922
18.960031509999993 37.96 37.08087101632086
Error at point 265, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 266
-8.67386818000005 0.6899999999999977 11.988910679999922
18.960031509999993 37.95 37.08087101632086
Error at point 266, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 267
-8.67386818000005 0.6799999999999997 11.988910679999922
18.960031509999993 37.92 37.08087101632086
Error at point 267, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 268
-8.67386818000005 0.6599999999999966 11.988910679999922
18.960031509999993 37.93 37.08087101632086
Error at point 268, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 269
-8.67386818000005 0.759999999999998 11.988910679999922
18.960031509999993 37.98 37.08087101632086
Error at point 269, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 270
-8.67386818000005 0.740000000000002 11.988910679999922
18.960031509999993 37.97 37.08087101632086
Error at point 270, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 271
-8.67386818000005 0.6099999999999994 11.988910679999922
18.960031509999993 37.84 37.08087101632086
Error at point 271, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
-8.67386818000005 6.420000000000002 11.988910679999922
18.960031509999993 8.699999999999996 37.08087101632086
Error at point 286, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
-8.67386818000005 0.3200000000000003 11.988910679999922
18.960031509999993 0.3200000000000003 37.08087101632086
Error at point 357, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
-8.67386818000005 6.0 11.988910679999922
18.960031509999993 38.0 37.08087101632086
Error at point 425, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 426
-8.67386818000005 6.0 11.988910679999922
18.960031509999993 37.8 37.08087101632086
Error at point 426, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 427
-8.67386818000005 6.0 11.988910679999922
18.960031509999993 37.6 37.08087101632086
Error at point 427, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 428
-8.67386818000005 5.899999999999999 11.988910679999922
18.960031509999993 38.0 37.08087101632086
Error at point 428, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 429
-8.67386818000005 5.799999999999997 11.988910679999922
18.960031509999993 37.8 37.08087101632086
Error at point 429, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 430
-8.67386818000005 5.799999999999997 11.988910679999922
18.960031509999993 37.7 37.08087101632086
Error at point 430, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 431
-8.67386818000005 5.899999999999999 11.988910679999922
18.960031509999993 38.1 37.08087101632086
Error at point 431, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 432
-8.67386818000005 5.700000000000003 11.988910679999922
18.960031509999993 37.7 37.08087101632086
Error at point 432, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 433
-8.67386818000005 5.700000000000003 11.988910679999922
18.960031509999993 37.6 37.08087101632086
Error at point 433, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 434
-8.67386818000005 5.600000000000001 11.988910679999922
18.960031509999993 37.6 37.08087101632086
Error at point 434, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 435
-8.67386818000005 5.600000000000001 11.988910679999922
18.960031509999993 37.5 37.08087101632086
Error at point 435, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 436
-8.67386818000005 0.0200000000000031 11.988910679999922
18.960031509999993 0.0 37.08087101632086
Error at point 436, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 437
-8.67386818000005 0.7299999999999969 11.988910679999922
18.960031509999993 0.2800000000000011 37.08087101632086
Error at point 437, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
Processing point 448
Processing point 449
Processing point 450
Processing point 451
Processing point 452
Processing point 453
Processing point 454
Processing point 455
Processing point 456
Processing point 457
Processing point 458
Processing point 459
Processing point 460
Processing point 461
Processing point 462
Processing point 463
Processing point 464
Processing point 465
Processing point 466
Processing point 467
Processing point 468
Processing point 469
Processing point 470
Processing point 471
Processing point 472
Processing point 473
Processing point 474
-8.67386818000005 44.72 11.988910679999922
18.960031509999993 21.13 37.08087101632086
Error at point 474, covariable 0
could not broadcast input array from shape (7,0) into shape (7,7)
Processing point 475
Processing point 476
Processing point 477
Processing point 478
Processing point 479
-8.67386818000005 1.2800000000000011 11.988910679999922
18.960031509999993 38.0 37.08087101632086
Error at point 479, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 480
Processing point 481
Processing point 482
Processing point 483
Processing point 484
Processing point 485
Processing point 486
Processing point 487
Processing point 488
Processing point 489
Processing point 490
Processing point 491
Processing point 492
Processing point 493
Processing point 494
Processing point 495

(496, 7, 7, 2)

In [ ]:
parent_window

In [ ]:
# shape file transformation
import geopandas as gpd
from rasterio.transform import from_bounds
from rasterio.features import rasterize

def transform_shape(shapefile_path , attribute , output_path):
    gdf = gpd.read_file(shapefile_path)
    gdf["category_numeric"], category_mapping = gdf[attribute].factorize()
    bounds = gdf.total_bounds  
    print("Bounds:", bounds)
    resolution = 0.008983  # -- 1KM
    width = int((bounds[2] - bounds[0]) / resolution)
    height = int((bounds[3] - bounds[1]) / resolution)

    print(f"Raster size: Width={width}, Height={height}")

    transform = from_bounds(*bounds, width, height)
    raster = rasterize(
        [(geom, value) for geom, value in zip(gdf.geometry, gdf["category_numeric"])],
        out_shape=(height, width),
        transform=transform,
        fill=-1, 
        dtype=rasterio.int32
    )

    tiff_path = output_path
    with rasterio.open(
        tiff_path, "w", 
        driver="GTiff",
        height=height, 
        width=width, 
        count=1,
        dtype=rasterio.uint8,
        crs=gdf.crs,  # Use same CRS as shapefile
        transform=transform
    ) as dst:
        dst.write(raster, 1)
    print(f"Saved 1 km raster to {tiff_path}")

In [ ]:
transform_shape("../Maps/ParentMaterial/Geomorphology/Algeria/Algeria_HG.shp" , "AlgGLG"  , "output_1km.tif")
geoMorpho_window = window_forming2("../Maps/ParentMaterial/Geomorphology/tiff" , df_unique)
np.save("../Data_multi_CNN/geoMorpho.npy", geoMorpho_window)
geoMorpho_window

In [78]:
class optimizerKhefoufi:
    def __init__(self , raster_data , transforme , src ):
        self.raster_data = raster_data
        self.transform = transforme
        self.src = src

def data_saver(path):
    files = []
    lat_min = 0 
    lat_max = 10

    lon_min = 30
    lon_max = 40


    for i in os.listdir(path):
        print(i)
        with rasterio.open(f"{path}/{i}") as src :
            raster_data = src.read()
            transform = src.transform 

            pixel_minx , pixel_miny = latlon_to_pixel(lat_min , lon_min ,src, transform)
            pixel_maxx , pixel_maxy = latlon_to_pixel(lat_max , lon_max , src , transform)
            print(pixel_minx , pixel_maxx , pixel_miny , pixel_maxy)
            
            raster_data = raster_data[0 , pixel_minx : pixel_maxx , pixel_miny : pixel_maxy]

            tiff_val = optimizerKhefoufi(raster_data , transform , src)
        files.append(tiff_val)
    return files
all_files = data_saver("../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data'

In [ ]:
Microbial_window = window_forming3(all_files , df_unique)
np.save("../Data_multi_CNN/microbial.npy", Microbial_window)
Microbial_window

In [46]:
def pixel_to_latlon(row, col, dataset):
    lon, lat = xy(dataset.transform, row, col)
    return lat, lon

In [47]:
windows = []
raster_data_used = "../Resmapled/organisme/evergreen.tif"
with rasterio.open(raster_data_used) as src: 
    raster = src.read()
    transform = src.transform

    for index in range(len(df_unique)):
        lat = df_unique.iloc[index]["X"]
        lon = df_unique.iloc[index]["Y"]

        pixel_row, pixel_col = latlon_to_pixel(lat, lon, src, transform)
        window = np.zeros((7, 7, 2))  # Only initialize once

        for i in range(pixel_row - 3, pixel_row + 4):  # rows (Y)
            for j in range(pixel_col - 3, pixel_col + 4):  # cols (X)
                lat_val, lon_val = pixel_to_latlon(i, j, src)

                row_idx = i - (pixel_row - 3)
                col_idx = j - (pixel_col - 3)

                window[row_idx, col_idx, 0] = lat_val
                window[row_idx, col_idx, 1] = lon_val

        windows.append(window)

# Check result
print(windows[0].shape)
np.save("../Data_multi_CNN/latlon.npy", windows)

(7, 7, 2)

In [28]:
windows

[array([[[ 1.33324104, 36.18646279],
         [ 1.33324104, 36.19115959],
         [ 1.33324104, 36.19585638],
         [ 1.33324104, 36.20055318],
         [ 1.33324104, 36.20524997],
         [ 1.33324104, 36.20994677],
         [ 1.33324104, 36.21464357]],

        [[ 1.32874942, 36.18646279],
         [ 1.32874942, 36.19115959],
         [ 1.32874942, 36.19585638],
         [ 1.32874942, 36.20055318],
         [ 1.32874942, 36.20524997],
         [ 1.32874942, 36.20994677],
         [ 1.32874942, 36.21464357]],

        [[ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357]],

        [[ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357]],

        [[ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357]],

        [[ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357]],

        [[ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357]]]),
 array([[[ 1.29281649, 37.98533556],
         [ 1.29281649, 37.99003236],
         [ 1.29281649, 37.99472915],
         [ 1.29281649, 37.99942595],
         [ 1.29281649, 38.00412274],
         [ 1.29281649, 38.00881954],
         [ 1.29281649, 38.01351633]],

        [[ 1.28832487, 37.98533556],
         [ 1.28832487, 37.99003236],
         [ 1.28832487, 37.99472915],
         [ 1.28832487, 37.99942595],
         [ 1.28832487, 38.00412274],
         [ 1.28832487, 38.00881954],
         [ 1.28832487, 38.01351633]],

        [[ 1.28383326, 37.98533556],
         [ 1.28383326, 37.99003236],
         [ 1.28383326, 37.99472915],
         [ 1.28383326, 37.99942595],
         [ 1.28383326, 38.00412274],
         [ 1.28383326, 38.00881954],
         [ 1.28383326, 38.01351633]],

        [[ 1.27934164, 37.98533556],
         [ 1.27934164, 37.99003236],
         [ 1.27934164, 37.99472915],
         [ 1.27934164, 37.99942595],
         [ 1.27934164, 38.00412274],
         [ 1.27934164, 38.00881954],
         [ 1.27934164, 38.01351633]],

        [[ 1.27485002, 37.98533556],
         [ 1.27485002, 37.99003236],
         [ 1.27485002, 37.99472915],
         [ 1.27485002, 37.99942595],
         [ 1.27485002, 38.00412274],
         [ 1.27485002, 38.00881954],
         [ 1.27485002, 38.01351633]],

        [[ 1.27035841, 37.98533556],
         [ 1.27035841, 37.99003236],
         [ 1.27035841, 37.99472915],
         [ 1.27035841, 37.99942595],
         [ 1.27035841, 38.00412274],
         [ 1.27035841, 38.00881954],
         [ 1.27035841, 38.01351633]],

        [[ 1.26586679, 37.98533556],
         [ 1.26586679, 37.99003236],
         [ 1.26586679, 37.99472915],
         [ 1.26586679, 37.99942595],
         [ 1.26586679, 38.00412274],
         [ 1.26586679, 38.00881954],
         [ 1.26586679, 38.01351633]]]),
 array([[[ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357]],

        [[ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357]],

        [[ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357]],

        [[ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357]],

        [[ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357]],

        [[ 1.30179972, 36.18646279],
         [ 1.30179972, 36.19115959],
         [ 1.30179972, 36.19585638],
         [ 1.30179972, 36.20055318],
         [ 1.30179972, 36.20524997],
         [ 1.30179972, 36.20994677],
         [ 1.30179972, 36.21464357]],

        [[ 1.29730811, 36.18646279],
         [ 1.29730811, 36.19115959],
         [ 1.29730811, 36.19585638],
         [ 1.29730811, 36.20055318],
         [ 1.29730811, 36.20524997],
         [ 1.29730811, 36.20994677],
         [ 1.29730811, 36.21464357]]]),
 array([[[ 1.31527457, 36.1770692 ],
         [ 1.31527457, 36.181766  ],
         [ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997]],

        [[ 1.31078296, 36.1770692 ],
         [ 1.31078296, 36.181766  ],
         [ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997]],

        [[ 1.30629134, 36.1770692 ],
         [ 1.30629134, 36.181766  ],
         [ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997]],

        [[ 1.30179972, 36.1770692 ],
         [ 1.30179972, 36.181766  ],
         [ 1.30179972, 36.18646279],
         [ 1.30179972, 36.19115959],
         [ 1.30179972, 36.19585638],
         [ 1.30179972, 36.20055318],
         [ 1.30179972, 36.20524997]],

        [[ 1.29730811, 36.1770692 ],
         [ 1.29730811, 36.181766  ],
         [ 1.29730811, 36.18646279],
         [ 1.29730811, 36.19115959],
         [ 1.29730811, 36.19585638],
         [ 1.29730811, 36.20055318],
         [ 1.29730811, 36.20524997]],

        [[ 1.29281649, 36.1770692 ],
         [ 1.29281649, 36.181766  ],
         [ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997]],

        [[ 1.28832487, 36.1770692 ],
         [ 1.28832487, 36.181766  ],
         [ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997]]]),
 array([[[ 1.33324104, 36.20524997],
         [ 1.33324104, 36.20994677],
         [ 1.33324104, 36.21464357],
         [ 1.33324104, 36.21934036],
         [ 1.33324104, 36.22403716],
         [ 1.33324104, 36.22873395],
         [ 1.33324104, 36.23343075]],

        [[ 1.32874942, 36.20524997],
         [ 1.32874942, 36.20994677],
         [ 1.32874942, 36.21464357],
         [ 1.32874942, 36.21934036],
         [ 1.32874942, 36.22403716],
         [ 1.32874942, 36.22873395],
         [ 1.32874942, 36.23343075]],

        [[ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357],
         [ 1.32425781, 36.21934036],
         [ 1.32425781, 36.22403716],
         [ 1.32425781, 36.22873395],
         [ 1.32425781, 36.23343075]],

        [[ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357],
         [ 1.31976619, 36.21934036],
         [ 1.31976619, 36.22403716],
         [ 1.31976619, 36.22873395],
         [ 1.31976619, 36.23343075]],

        [[ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357],
         [ 1.31527457, 36.21934036],
         [ 1.31527457, 36.22403716],
         [ 1.31527457, 36.22873395],
         [ 1.31527457, 36.23343075]],

        [[ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357],
         [ 1.31078296, 36.21934036],
         [ 1.31078296, 36.22403716],
         [ 1.31078296, 36.22873395],
         [ 1.31078296, 36.23343075]],

        [[ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357],
         [ 1.30629134, 36.21934036],
         [ 1.30629134, 36.22403716],
         [ 1.30629134, 36.22873395],
         [ 1.30629134, 36.23343075]]]),
 array([[[ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997],
         [ 1.29281649, 36.20994677],
         [ 1.29281649, 36.21464357]],

        [[ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997],
         [ 1.28832487, 36.20994677],
         [ 1.28832487, 36.21464357]],

        [[ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638],
         [ 1.28383326, 36.20055318],
         [ 1.28383326, 36.20524997],
         [ 1.28383326, 36.20994677],
         [ 1.28383326, 36.21464357]],

        [[ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638],
         [ 1.27934164, 36.20055318],
         [ 1.27934164, 36.20524997],
         [ 1.27934164, 36.20994677],
         [ 1.27934164, 36.21464357]],

        [[ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997],
         [ 1.27485002, 36.20994677],
         [ 1.27485002, 36.21464357]],

        [[ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997],
         [ 1.27035841, 36.20994677],
         [ 1.27035841, 36.21464357]],

        [[ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997],
         [ 1.26586679, 36.20994677],
         [ 1.26586679, 36.21464357]]]),
 array([[[ 1.29281649, 36.1770692 ],
         [ 1.29281649, 36.181766  ],
         [ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997]],

        [[ 1.28832487, 36.1770692 ],
         [ 1.28832487, 36.181766  ],
         [ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997]],

        [[ 1.28383326, 36.1770692 ],
         [ 1.28383326, 36.181766  ],
         [ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638],
         [ 1.28383326, 36.20055318],
         [ 1.28383326, 36.20524997]],

        [[ 1.27934164, 36.1770692 ],
         [ 1.27934164, 36.181766  ],
         [ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638],
         [ 1.27934164, 36.20055318],
         [ 1.27934164, 36.20524997]],

        [[ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997]],

        [[ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997]],

        [[ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997]]]),
 array([[[ 1.30179972, 36.22403716],
         [ 1.30179972, 36.22873395],
         [ 1.30179972, 36.23343075],
         [ 1.30179972, 36.23812754],
         [ 1.30179972, 36.24282434],
         [ 1.30179972, 36.24752114],
         [ 1.30179972, 36.25221793]],

        [[ 1.29730811, 36.22403716],
         [ 1.29730811, 36.22873395],
         [ 1.29730811, 36.23343075],
         [ 1.29730811, 36.23812754],
         [ 1.29730811, 36.24282434],
         [ 1.29730811, 36.24752114],
         [ 1.29730811, 36.25221793]],

        [[ 1.29281649, 36.22403716],
         [ 1.29281649, 36.22873395],
         [ 1.29281649, 36.23343075],
         [ 1.29281649, 36.23812754],
         [ 1.29281649, 36.24282434],
         [ 1.29281649, 36.24752114],
         [ 1.29281649, 36.25221793]],

        [[ 1.28832487, 36.22403716],
         [ 1.28832487, 36.22873395],
         [ 1.28832487, 36.23343075],
         [ 1.28832487, 36.23812754],
         [ 1.28832487, 36.24282434],
         [ 1.28832487, 36.24752114],
         [ 1.28832487, 36.25221793]],

        [[ 1.28383326, 36.22403716],
         [ 1.28383326, 36.22873395],
         [ 1.28383326, 36.23343075],
         [ 1.28383326, 36.23812754],
         [ 1.28383326, 36.24282434],
         [ 1.28383326, 36.24752114],
         [ 1.28383326, 36.25221793]],

        [[ 1.27934164, 36.22403716],
         [ 1.27934164, 36.22873395],
         [ 1.27934164, 36.23343075],
         [ 1.27934164, 36.23812754],
         [ 1.27934164, 36.24282434],
         [ 1.27934164, 36.24752114],
         [ 1.27934164, 36.25221793]],

        [[ 1.27485002, 36.22403716],
         [ 1.27485002, 36.22873395],
         [ 1.27485002, 36.23343075],
         [ 1.27485002, 36.23812754],
         [ 1.27485002, 36.24282434],
         [ 1.27485002, 36.24752114],
         [ 1.27485002, 36.25221793]]]),
 array([[[ 1.28383326, 36.16767561],
         [ 1.28383326, 36.1723724 ],
         [ 1.28383326, 36.1770692 ],
         [ 1.28383326, 36.181766  ],
         [ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638]],

        [[ 1.27934164, 36.16767561],
         [ 1.27934164, 36.1723724 ],
         [ 1.27934164, 36.1770692 ],
         [ 1.27934164, 36.181766  ],
         [ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638]],

        [[ 1.27485002, 36.16767561],
         [ 1.27485002, 36.1723724 ],
         [ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638]],

        [[ 1.27035841, 36.16767561],
         [ 1.27035841, 36.1723724 ],
         [ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638]],

        [[ 1.26586679, 36.16767561],
         [ 1.26586679, 36.1723724 ],
         [ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638]],

        [[ 1.26137517, 36.16767561],
         [ 1.26137517, 36.1723724 ],
         [ 1.26137517, 36.1770692 ],
         [ 1.26137517, 36.181766  ],
         [ 1.26137517, 36.18646279],
         [ 1.26137517, 36.19115959],
         [ 1.26137517, 36.19585638]],

        [[ 1.25688356, 36.16767561],
         [ 1.25688356, 36.1723724 ],
         [ 1.25688356, 36.1770692 ],
         [ 1.25688356, 36.181766  ],
         [ 1.25688356, 36.18646279],
         [ 1.25688356, 36.19115959],
         [ 1.25688356, 36.19585638]]]),
 array([[[ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997]],

        [[ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997]],

        [[ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997]],

        [[ 1.26137517, 36.1770692 ],
         [ 1.26137517, 36.181766  ],
         [ 1.26137517, 36.18646279],
         [ 1.26137517, 36.19115959],
         [ 1.26137517, 36.19585638],
         [ 1.26137517, 36.20055318],
         [ 1.26137517, 36.20524997]],

        [[ 1.25688356, 36.1770692 ],
         [ 1.25688356, 36.181766  ],
         [ 1.25688356, 36.18646279],
         [ 1.25688356, 36.19115959],
         [ 1.25688356, 36.19585638],
         [ 1.25688356, 36.20055318],
         [ 1.25688356, 36.20524997]],

        [[ 1.25239194, 36.1770692 ],
         [ 1.25239194, 36.181766  ],
         [ 1.25239194, 36.18646279],
         [ 1.25239194, 36.19115959],
         [ 1.25239194, 36.19585638],
         [ 1.25239194, 36.20055318],
         [ 1.25239194, 36.20524997]],

        [[ 1.24790032, 36.1770692 ],
         [ 1.24790032, 36.181766  ],
         [ 1.24790032, 36.18646279],
         [ 1.24790032, 36.19115959],
         [ 1.24790032, 36.19585638],
         [ 1.24790032, 36.20055318],
         [ 1.24790032, 36.20524997]]]),
 array([[[ 1.33324104, 36.1770692 ],
         [ 1.33324104, 36.181766  ],
         [ 1.33324104, 36.18646279],
         [ 1.33324104, 36.19115959],
         [ 1.33324104, 36.19585638],
         [ 1.33324104, 36.20055318],
         [ 1.33324104, 36.20524997]],

        [[ 1.32874942, 36.1770692 ],
         [ 1.32874942, 36.181766  ],
         [ 1.32874942, 36.18646279],
         [ 1.32874942, 36.19115959],
         [ 1.32874942, 36.19585638],
         [ 1.32874942, 36.20055318],
         [ 1.32874942, 36.20524997]],

        [[ 1.32425781, 36.1770692 ],
         [ 1.32425781, 36.181766  ],
         [ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997]],

        [[ 1.31976619, 36.1770692 ],
         [ 1.31976619, 36.181766  ],
         [ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997]],

        [[ 1.31527457, 36.1770692 ],
         [ 1.31527457, 36.181766  ],
         [ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997]],

        [[ 1.31078296, 36.1770692 ],
         [ 1.31078296, 36.181766  ],
         [ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997]],

        [[ 1.30629134, 36.1770692 ],
         [ 1.30629134, 36.181766  ],
         [ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],

In [ ]:
transform_shape("../Maps/ParentMaterial/Rock_type/geo7_2ag.shp" , "GLG"  , "../Maps/ParentMaterial/Rock_type/tiff/rocksType_1km.tif")
rocks_window = window_forming("../Maps/ParentMaterial/Rock_type/tiff", df_unique)
np.save("../Data_multi_CNN/rocks.npy", rocks_window)
rocks_window

,AREA,PERIMETER,GEO2_7G_,GEO2_7G_ID,GLG,geometry,category_numeric
0,2250.44404,966.65344,2,11939,SEA,"POLYGON ((5.40701 5.57146, 5.4109 5.4694, 5.42...",0
1,1.60529,7.58497,3,6,oth,"POLYGON ((15.64759 40.00266, 15.66 40, 15.676 ...",1
2,7.02790,33.05255,4,3,oth,"POLYGON ((19.89965 39.96591, 22.81549 39.8342,...",1
3,0.06592,1.66218,5,7,oth,"POLYGON ((19.67681 39.78778, 19.7106 39.7867, ...",1
4,0.90818,4.50544,6,4,oth,"POLYGON ((8.40944 39.76892, 9.63446 39.84441, ...",1
...,...,...,...,...,...,...,...
11972,0.01677,0.69987,11974,11935,SO,"POLYGON ((19.69988 -34.58595, 19.70456 -34.581...",31
11973,0.00456,0.35706,11975,11936,D,"POLYGON ((19.69988 -34.58595, 19.70059 -34.602...",27
11974,0.00239,0.20456,11976,11934,pCm,"POLYGON ((19.43258 -34.60229, 19.40437 -34.627...",11
11975,0.00641,0.35766,11977,11938,SO,"POLYGON ((19.84761 -34.67162, 19.85932 -34.661...",31
11976,0.00790,0.45490,11978,11937,pCm,"POLYGON ((19.84761 -34.67162, 19.85032 -34.677...",11

In [53]:
def outputs_building(df ,df_unique, atr):
    depth_ranges = [
        (0, 15),
        (5, 15),
        (15, 30),
        (30, 60),
        (60, 100),
        (100, 200)
    ]
    result_array = np.zeros((474, 6))
    depth_indices = {i: [] for i in range(len(depth_ranges))}

    for i, (lb, ub) in enumerate(depth_ranges):
        for j in range(lb, ub + 1):
            depth_indices[i].append(j)
    
    for _, row in df.iterrows():
        x, y, ud, ld, val = row['X'], row['Y'], row['UD'], row['LD'] , row[atr]
        for index, depth_range in depth_indices.items():
            if any(d in range(int(ud), int(ld) + 1) for d in depth_range):
                result_array[df_unique[(df_unique['X'] == x) & (df_unique['Y'] == y)].index[0], index] = val

    mean = df[atr].mean()
    result_array = np.nan_to_num(result_array, nan=mean)
    finals = np.array(result_array).reshape(474,6,1)
    for i in finals:
        print(i)
    
    print(finals.shape)
    return finals

In [56]:
df_unique = df_unique.reset_index()
df_unique

,index,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,0,1.32,36.20,0,5,2.5,1.316667,0.233333,8.544,7.333333,2.166667,2.500000,20.256,4.843655,0.216667
1,8,1.28,38.00,0,5,2.5,1.316667,0.233333,12.040,7.333333,2.166667,2.500000,1.940,2.457421,0.216667
2,16,1.31,36.20,0,5,2.5,0.914634,0.060976,8.544,5.365854,1.829268,1.707317,20.256,4.843655,0.146341
3,25,1.30,36.19,0,5,2.5,1.054054,0.054054,8.544,6.621622,2.702703,1.216216,20.256,4.843655,0.162162
4,34,1.32,36.22,0,5,2.5,1.218750,0.093750,8.544,4.218750,1.406250,2.500000,20.256,4.843655,0.234375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,2612,2.41,27.18,0,23,11.5,8.430000,20.000000,6.720,0.460000,6.800000,87.752000,59.032,8.702000,0.800000
470,2615,2.25,27.35,0,20,10.0,7.630000,1.150000,4.182,1.822000,5.584000,88.490000,42.300,8.896000,2.380000
471,2619,2.41,27.96,0,10,5.0,6.720000,3.710000,4.182,1.500000,2.484000,91.626000,47.416,8.374000,1.060000
472,2624,2.45,27.20,0,3,1.5,6.800000,3.750000,4.182,1.500000,2.484000,91.626000,39.720,8.374000,1.320000
473,2627,2.43,27.19,0,8,4.0,7.390000,2.860000,4.182,1.500000,5.584000,88.490000,41.090,8.896000,1.430000

In [58]:
df_unique = df_unique.drop(columns=["index"])
df_unique

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,1.32,36.20,0,5,2.5,1.316667,0.233333,8.544,7.333333,2.166667,2.500000,20.256,4.843655,0.216667
1,1.28,38.00,0,5,2.5,1.316667,0.233333,12.040,7.333333,2.166667,2.500000,1.940,2.457421,0.216667
2,1.31,36.20,0,5,2.5,0.914634,0.060976,8.544,5.365854,1.829268,1.707317,20.256,4.843655,0.146341
3,1.30,36.19,0,5,2.5,1.054054,0.054054,8.544,6.621622,2.702703,1.216216,20.256,4.843655,0.162162
4,1.32,36.22,0,5,2.5,1.218750,0.093750,8.544,4.218750,1.406250,2.500000,20.256,4.843655,0.234375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,2.41,27.18,0,23,11.5,8.430000,20.000000,6.720,0.460000,6.800000,87.752000,59.032,8.702000,0.800000
470,2.25,27.35,0,20,10.0,7.630000,1.150000,4.182,1.822000,5.584000,88.490000,42.300,8.896000,2.380000
471,2.41,27.96,0,10,5.0,6.720000,3.710000,4.182,1.500000,2.484000,91.626000,47.416,8.374000,1.060000
472,2.45,27.20,0,3,1.5,6.800000,3.750000,4.182,1.500000,2.484000,91.626000,39.720,8.374000,1.320000
473,2.43,27.19,0,8,4.0,7.390000,2.860000,4.182,1.500000,5.584000,88.490000,41.090,8.896000,1.430000

In [ ]:
df

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,1.32,36.20,0.0,5.0,2.5,1.316667,0.233333,8.544000,7.333333,2.166667,2.500,20.256000,4.843655,0.216667
1,1.32,36.20,5.0,15.0,10.0,2.633333,0.466667,8.126000,14.666667,4.333333,5.000,20.256000,4.853527,0.433333
2,1.32,36.20,15.0,30.0,22.5,3.950000,0.700000,16.186191,22.000000,6.500000,7.500,19.814000,0.138530,0.650000
3,1.32,36.20,30.0,60.0,45.0,5.333333,0.333333,11.876000,30.666667,10.666667,10.000,34.226429,-0.162834,0.800000
4,1.32,36.20,60.0,100.0,80.0,2.666667,0.166667,10.206000,15.333333,5.333333,5.000,74.816000,0.248837,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2627,2.43,27.19,0.0,8.0,4.0,7.390000,2.860000,4.182000,1.500000,5.584000,88.490,41.090000,8.896000,1.430000
2628,2.43,27.19,8.0,34.0,21.0,7.650000,4.870000,4.352000,0.406000,14.524000,85.736,46.690000,8.896000,0.530000
2629,2.43,27.19,34.0,43.0,38.5,7.990000,5.480000,3.246000,0.214000,9.618000,87.536,38.250000,7.354000,1.060000
2630,2.43,27.19,43.0,60.0,51.5,8.040000,4.070000,2.914000,0.194000,4.398000,92.376,34.214000,7.354000,0.000000
2631,2.43,27.19,60.0,80.0,70.0,7.900000,3.130000,2.048000,0.190000,4.398000,92.376,38.850000,7.088000,0.000000

In [61]:
for i in df.columns[5:]:
    print(i)
    finals = outputs_building(df ,df_unique, i)
    np.save(f'../Data_multi_CNN/output{i}.npy', np.array(finals))

pH
[[0.23235294]
 [0.23235294]
 [6.97058824]
 [0.77878676]
 [8.06      ]
 [8.06      ]]
[[3.95      ]
 [3.95      ]
 [5.33333333]
 [4.44444444]
 [8.        ]
 [8.        ]]
[[2.74390244]
 [2.74390244]
 [4.43333333]
 [5.05555556]
 [8.        ]
 [8.        ]]
[[3.77419355]
 [3.77419355]
 [7.159375  ]
 [0.740625  ]
 [0.740625  ]
 [0.740625  ]]
[[3.65625]
 [3.65625]
 [6.825  ]
 [7.8    ]
 [7.8    ]
 [7.8    ]]
[[3.12857143]
 [3.12857143]
 [4.5625    ]
 [2.80769231]
 [4.49230769]
 [4.49230769]]
[[3.        ]
 [3.        ]
 [4.82352941]
 [6.04324324]
 [8.6       ]
 [8.6       ]]
[[3.95      ]
 [3.95      ]
 [5.92682927]
 [5.94871795]
 [2.05128205]
 [2.05128205]]
[[3.075     ]
 [3.075     ]
 [2.96666667]
 [5.93333333]
 [9.        ]
 [9.        ]]
[[3.375     ]
 [3.375     ]
 [0.92718615]
 [5.18862745]
 [5.18862745]
 [5.18862745]]
[[3.85      ]
 [3.85      ]
 [4.74      ]
 [2.63333333]
 [8.06      ]
 [8.06      ]]
[[3.22058824]
 [3.22058824]
 [5.2       ]
 [2.56925742]
 [4.53012821]
 [4.53012821]]
[[0.975 ]
 [0.975 ]
 [5.85  ]
 [6.9125]
 [7.6   ]
 [7.6   ]]
[[2.75]
 [2.75]
 [3.6 ]
 [3.85]
 [3.85]
 [3.85]]
[[2.44897959]
 [2.44897959]
 [4.19047619]
 [5.26666667]
 [8.06      ]
 [8.06      ]]
[[3.34285714]
 [3.34285714]
 [3.09840816]
 [0.77878676]
 [4.53012821]
 [4.53012821]]
[[3.23061702]
 [3.23061702]
 [5.17980657]
 [5.32733997]
 [4.28      ]
 [4.28      ]]
[[3.23061702]
 [3.23061702]
 [5.17980657]
 [5.32733997]
 [2.5920756 ]
 [2.5920756 ]]
[[7.87 ]
 [7.87 ]
 [7.774]
 [7.799]
 [7.799]
 [7.799]]
[[7.95 ]
 [7.95 ]
 [8.096]
 [8.096]
 [8.096]
 [0.   ]]
[[8.5]
 [8.5]
 [8.5]
 [8.5]
 [8.5]
 [0. ]]
[[8.59]
 [8.59]
 [8.59]
 [8.59]
 [0.  ]
 [0.  ]]
[[7.83]
 [7.83]
 [7.83]
 [7.83]
 [7.83]
 [0.  ]]
[[7.2]
 [7.2]
 [7.2]
 [7.8]
 [7.8]
 [7.8]]
[[8.5]
 [8.5]
 [8.5]
 [8.5]
 [8.5]
 [0. ]]
[[7.182]
 [7.182]
 [7.457]
 [7.619]
 [7.619]
 [7.619]]
[[7.893]
 [7.893]
 [7.86 ]
 [7.828]
 [7.828]
 [7.828]]
[[7.123]
 [7.123]
 [7.143]
 [7.105]
 [7.105]
 [7.105]]
[[7.304]
 [7.304]
 [7.207]
 [7.28 ]
 [7.28 ]
 [7.28 ]]
[[7.603]
 [7.603]
 [7.52 ]
 [7.489]
 [7.489]
 [7.489]]
[[7.73 ]
 [7.73 ]
 [7.519]
 [7.411]
 [7.411]
 [7.411]]
[[7.816]
 [7.816]
 [7.685]
 [7.582]
 [7.582]
 [7.582]]
[[8.006]
 [8.006]
 [8.097]
 [8.133]
 [8.133]
 [8.133]]
[[7.713]
 [7.713]
 [7.892]
 [7.852]
 [7.852]
 [7.852]]
[[7.801]
 [7.801]
 [7.798]
 [7.801]
 [7.801]
 [7.801]]
[[7.22 ]
 [7.22 ]
 [7.189]
 [7.126]
 [7.126]
 [7.126]]
[[7.205]
 [7.205]
 [7.077]
 [7.085]
 [7.085]
 [7.085]]
[[8.3]
 [8.3]
 [8.3]
 [8.3]
 [0. ]
 [0. ]]
[[7.69]
 [7.69]
 [7.69]
 [7.69]
 [7.69]
 [0.  ]]
[[7.968]
 [7.968]
 [8.027]
 [8.027]
 [8.027]
 [0.   ]]
[[7.758]
 [7.758]
 [7.888]
 [7.888]
 [7.888]
 [0.   ]]
[[8.309]
 [8.309]
 [8.353]
 [8.353]
 [8.353]
 [0.   ]]
[[8.262]
 [8.262]
 [8.386]
 [8.386]
 [8.386]
 [0.   ]]
[[8.351]
 [8.351]
 [8.491]
 [8.491]
 [8.491]
 [0.   ]]
[[8.415]
 [8.415]
 [8.62 ]
 [8.62 ]
 [8.62 ]
 [0.   ]]
[[8.086]
 [8.086]
 [7.978]
 [7.978]
 [7.978]
 [0.   ]]
[[8.189]
 [8.189]
 [8.205]
 [8.205]
 [8.205]
 [0.   ]]
[[7.525]
 [7.525]
 [7.546]
 [7.546]
 [7.546]
 [0.   ]]
[[8.26]
 [8.26]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[6.8]
 [6.8]
 [6.8]
 [6.8]
 [0. ]
 [0. ]]
[[8.71]
 [8.71]
 [8.94]
 [8.94]
 [8.94]
 [8.94]]
[[8.77 ]
 [8.77 ]
 [8.731]
 [8.731]
 [8.731]
 [0.   ]]
[[8.429]
 [8.429]
 [8.711]
 [8.711]
 [8.711]
 [0.   ]]
[[8.61]
 [8.61]
 [8.61]
 [8.61]
 [8.61]
 [8.51]]
[[8.37]
 [8.37]
 [8.37]
 [8.37]
 [8.37]
 [0.  ]]
[[8.8 ]
 [8.8 ]
 [8.8 ]
 [8.8 ]
 [8.71]
 [0.  ]]
[[8.729]
 [8.729]
 [8.729]
 [8.729]
 [0.   ]
 [0.   ]]
[[8.64]
 [8.64]
 [8.64]
 [8.64]
 [8.64]
 [0.  ]]
[[8.122]
 [8.122]
 [8.108]
 [8.31 ]
 [8.653]
 [8.653]]
[[8.757]
 [8.757]
 [8.742]
 [8.379]
 [8.525]
 [8.525]]
[[8.251]
 [8.251]
 [8.413]
 [8.237]
 [8.071]
 [8.071]]
[[8.369]
 [8.369]
 [8.597]
 [8.593]
 [8.602]
 [8.602]]
[[7.99]
 [7.99]
 [7.99]
 [7.99]
 [7.99]
 [0.  ]]
[[0.817]
 [0.817]
 [0.817]
 [0.817]
 [0.   ]
 [0.   ]]
[[7.65 ]
 [7.65 ]
 [7.592]
 [7.592]
 [7.592]
 [0.   ]]
[[8.11]
 [8.11]
 [8.11]
 [8.11]
 [8.11]
 [0.  ]]
[[8.2]
 [8.2]
 [8.2]
 [8.2]
 [8.2]
 [0. ]]
[[7.15]
 [7.15]
 [7.15]
 [7.15]
 [0.  ]
 [0.  ]]
[[6.286]
 [6.286]
 [5.939]
 [6.239]
 [6.239]
 [6.239]]
[[7.1]
 [7.1]
 [7.1]
 [7.1]
 [7.1]
 [0. ]]
[[6.21]
 [6.21]
 [6.21]
 [6.21]
 [6.21]
 [0.  ]]
[[5.53]
 [5.53]
 [5.53]
 [5.53]
 [5.53]
 [0.  ]]
[[6.94]
 [6.94]
 [6.94]
 [6.94]
 [0.  ]
 [0.  ]]
[[7.03]
 [7.03]
 [7.03]
 [7.03]
 [7.03]
 [0.  ]]
[[7.14]
 [7.14]
 [7.14]
 [7.14]
 [7.14]
 [0.  ]]
[[7.06]
 [7.06]
 [7.06]
 [7.06]
 [7.06]
 [0.  ]]
[[7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [0.  ]]
[[6.73]
 [6.73]
 [6.73]
 [6.73]
 [6.73]
 [0.  ]]
[[7.09698381]
 [7.09698381]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.09698381]
 [7.09698381]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.09698381]
 [7.09698381]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.8]
 [7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.7]
 [7.7]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.6]
 [7.6]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.5]
 [7.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.4]
 [8.4]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.3]
 [8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.3]
 [8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.3]
 [8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.4]
 [7.4]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.7]
 [7.7]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.3]
 [8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.]
 [8.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.378]
 [8.378]
 [8.494]
 [8.665]
 [8.649]
 [8.649]]
[[8.705]
 [8.705]
 [8.904]
 [8.884]
 [8.867]
 [8.867]]
[[8.666]
 [8.666]
 [8.639]
 [8.538]
 [8.375]
 [8.375]]
[[8.686]
 [8.686]
 [8.183]
 [8.104]
 [8.104]
 [8.104]]
[[8.843]
 [8.843]
 [8.766]
 [8.678]
 [8.678]
 [8.678]]
[[8.258]
 [8.258]
 [8.509]
 [8.475]
 [8.358]
 [8.358]]
[[8.22]
 [8.22]
 [8.22]
 [8.22]
 [0.  ]
 [0.  ]]
[[8.405]
 [8.405]
 [8.196]
 [8.257]
 [8.395]
 [8.395]]
[[8.17 ]
 [8.17 ]
 [8.526]
 [8.334]
 [8.688]
 [8.688]]
[[7.879]
 [7.879]
 [7.672]
 [7.715]
 [7.478]
 [7.478]]
[[7.542]
 [7.542]
 [7.43 ]
 [7.244]
 [7.244]
 [7.244]]
[[7.78]
 [7.78]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.61]
 [7.61]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.04]
 [8.04]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.65]
 [7.65]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.74]
 [7.74]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.45]
 [7.45]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.74]
 [7.74]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.83]
 [7.83]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.49]
 [7.49]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.2]
 [7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]]
[[7.3]
 [7.3]
 [7.3]
 [7.3]
 [0. ]
 [0. ]]
[[7.81]
 [7.81]
 [7.81]
 [7.81]
 [0.  ]
 [0.  ]]
[[7.22]
 [7.22]
 [7.22]
 [7.22]
 [0.  ]
 [0.  ]]
[[7.45]
 [7.45]
 [7.45]
 [7.45]
 [0.  ]
 [0.  ]]
[[7.86]
 [7.86]
 [7.86]
 [7.86]
 [0.  ]
 [0.  ]]
[[8.12]
 [8.12]
 [8.12]
 [8.12]
 [0.  ]
 [0.  ]]
[[8.3]
 [8.3]
 [8.3]
 [8.3]
 [0. ]
 [0. ]]
[[8.27]
 [8.27]
 [8.27]
 [8.27]
 [0.  ]
 [0.  ]]
[[8.222]
 [8.222]
 [8.222]
 [8.222]
 [0.   ]
 [0.   ]]
[[8.48]
 [8.48]
 [8.48]
 [8.48]
 [0.  ]
 [0.  ]]
[[8.27]
 [8.27]
 [8.27]
 [8.27]
 [0.  ]
 [0.  ]]
[[8.427]
 [8.427]
 [8.427]
 [8.427]
 [0.   ]
 [0.   ]]
[[5.53 ]
 [5.53 ]
 [5.225]
 [5.304]
 [5.568]
 [5.568]]
[[4.481]
 [4.481]
 [4.655]
 [5.081]
 [4.876]
 [4.876]]
[[4.866]
 [4.866]
 [4.702]
 [4.337]
 [4.102]
 [4.102]]
[[4.8  ]
 [4.8  ]
 [4.843]
 [4.946]
 [4.85 ]
 [4.85 ]]
[[8.08364286]
 [8.08364286]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.08364286]
 [8.08364286]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.02967532]
 [8.02967532]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.08364286]
 [8.08364286]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.02967532]
 [8.02967532]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.692]
 [7.692]
 [7.692]
 [7.692]
 [0.   ]
 [0.   ]]
[[7.44]
 [7.44]
 [7.44]
 [7.44]
 [0.  ]
 [0.  ]]
[[8.51]
 [8.51]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.5]
 [8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.41]
 [8.41]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.36]
 [8.36]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.76]
 [8.76]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]
[[5.841]
 [5.841]
 [5.533]
 [5.282]
 [5.282]
 [5.282]]
[[6.563]
 [6.563]
 [6.369]
 [6.227]
 [6.227]
 [6.227]]
[[6.538]
 [6.538]
 [6.155]
 [5.894]
 [5.894]
 [5.894]]
[[6.424]
 [6.424]
 [6.507]
 [6.358]
 [6.248]
 [6.248]]
[[6.074]
 [6.074]
 [5.621]
 [5.356]
 [5.224]
 [5.224]]
[[5.33]
 [5.33]
 [5.33]
 [5.33]
 [0.  ]
 [0.  ]]
[[6.119]
 [6.119]
 [6.194]
 [6.309]
 [6.389]
 [6.389]]
[[6.053]
 [6.053]
 [6.412]
 [6.613]
 [6.514]
 [6.514]]
[[6.473]
 [6.473]
 [6.768]
 [6.862]
 [6.628]
 [6.628]]
[[6.512]
 [6.512]
 [6.566]
 [6.817]
 [6.897]
 [6.897]]
[[5.998]
 [5.998]
 [5.579]
 [5.352]
 [5.787]
 [5.787]]
[[5.703]
 [5.703]
 [5.762]
 [6.333]
 [6.441]
 [6.441]]
[[6.77 ]
 [6.77 ]
 [6.619]
 [6.619]
 [6.619]
 [0.   ]]
[[6.331]
 [6.331]
 [6.339]
 [6.543]
 [6.612]
 [6.612]]
[[7.5]
 [7.5]
 [7.5]
 [0. ]
 [0. ]
 [0. ]]
[[7.298]
 [7.298]
 [7.98 ]
 [7.98 ]
 [7.8  ]
 [0.   ]]
[[7.22]
 [7.22]
 [7.22]
 [7.56]
 [7.56]
 [0.  ]]
[[7.89]
 [7.89]
 [7.89]
 [7.84]
 [7.84]
 [0.  ]]
[[7.28]
 [7.28]
 [7.28]
 [7.25]
 [7.25]
 [0.  ]]
[[7.7 ]
 [7.7 ]
 [7.7 ]
 [7.45]
 [7.45]
 [0.  ]]
[[7.8 ]
 [7.8 ]
 [7.8 ]
 [7.62]
 [7.62]
 [0.  ]]
[[8.02]
 [8.02]
 [8.02]
 [8.12]
 [8.12]
 [0.  ]]
[[7.75]
 [7.75]
 [7.75]
 [7.87]
 [7.87]
 [0.  ]]
[[7.8]
 [7.8]
 [7.8]
 [7.8]
 [7.8]
 [0. ]]
[[7.22]
 [7.22]
 [7.22]
 [7.15]
 [7.15]
 [0.  ]]
[[7.18]
 [7.18]
 [7.18]
 [7.08]
 [7.08]
 [0.  ]]
[[7.27]
 [7.27]
 [7.27]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.27]
 [7.27]
 [7.27]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.27]
 [7.27]
 [7.27]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.27]
 [7.27]
 [7.27]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.69]
 [7.69]
 [7.69]
 [7.69]
 [0.  ]
 [0.  ]]
[[7.69]
 [7.69]
 [7.69]
 [7.69]
 [0.  ]
 [0.  ]]
[[7.9 ]
 [7.9 ]
 [8.01]
 [8.01]
 [0.  ]
 [0.  ]]
[[7.61]
 [7.61]
 [7.85]
 [7.85]
 [0.  ]
 [0.  ]]
[[8.26]
 [8.26]
 [8.34]
 [8.34]
 [0.  ]
 [0.  ]]
[[8.12]
 [8.12]
 [8.35]
 [8.35]
 [0.  ]
 [0.  ]]
[[8.18]
 [8.18]
 [8.56]
 [8.56]
 [0.  ]
 [0.  ]]
[[8.21]
 [8.21]
 [8.01]
 [8.01]
 [0.  ]
 [0.  ]]
[[7.5 ]
 [7.5 ]
 [7.54]
 [7.54]
 [0.  ]
 [0.  ]]
[[8.55]
 [8.55]
 [8.55]
 [8.55]
 [0.  ]
 [0.  ]]
[[7.83]
 [7.83]
 [7.83]
 [7.83]
 [0.  ]
 [0.  ]]
[[7.92]
 [7.92]
 [7.92]
 [7.92]
 [0.  ]
 [0.  ]]
[[6.8]
 [6.8]
 [6.8]
 [0. ]
 [0. ]
 [0. ]]
[[7.344]
 [7.344]
 [7.134]
 [8.398]
 [8.34 ]
 [8.34 ]]
[[8.86]
 [8.86]
 [8.51]
 [8.82]
 [8.82]
 [8.82]]
[[8.74]
 [8.74]
 [8.37]
 [8.37]
 [0.  ]
 [0.  ]]
[[7.7]
 [7.7]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[5.6]
 [5.6]
 [5.2]
 [5.2]
 [5.5]
 [5.5]]
[[0. ]
 [0. ]
 [6.5]
 [6.5]
 [5.2]
 [4.4]]
[[5.8]
 [5.8]
 [5.8]
 [5.5]
 [5.5]
 [5.2]]
[[5.6]
 [5.6]
 [5.6]
 [5.5]
 [4.8]
 [4.1]]
[[5.2]
 [5.2]
 [5.2]
 [5.2]
 [4.6]
 [4.6]]
[[ 5.2]
 [ 5.2]
 [ 5.2]
 [ 4.6]
 [ 4.6]
 [29.8]]
[[5.6]
 [5.6]
 [5.5]
 [5.5]
 [5.4]
 [5.2]]
[[5.6]
 [5.6]
 [5.6]
 [5.5]
 [5.5]
 [5.3]]
[[8.3]
 [8.3]
 [8.7]
 [8.7]
 [8.3]
 [8.3]]
[[8.1]
 [8.1]
 [8.4]
 [8.4]
 [8.3]
 [8. ]]
[[8.3]
 [8.3]
 [8.6]
 [8.6]
 [8.6]
 [8.6]]
[[8.38]
 [8.38]
 [8.  ]
 [8.  ]
 [0.  ]
 [0.  ]]
[[6.5]
 [6.5]
 [6.5]
 [0. ]
 [0. ]
 [0. ]]
[[6.8]
 [6.8]
 [7.5]
 [0. ]
 [0. ]
 [0. ]]
[[7.2]
 [7.2]
 [7.5]
 [7.5]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [8.2]
 [8.2]
 [0. ]
 [0. ]]
[[7.5]
 [7.5]
 [7.5]
 [0. ]
 [0. ]
 [0. ]]
[[7.]
 [7.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[7.2]
 [7.2]
 [7.5]
 [7.5]
 [0. ]
 [0. ]]
[[7.3]
 [7.3]
 [7.3]
 [0. ]
 [0. ]
 [0. ]]
[[6.5]
 [6.5]
 [6.5]
 [0. ]
 [0. ]
 [0. ]]
[[7.]
 [7.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[7.3]
 [7.3]
 [7.3]
 [0. ]
 [0. ]
 [0. ]]
[[7.4]
 [7.4]
 [7.4]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [7.9]
 [7.9]
 [8. ]
 [8. ]
 [8. ]]
[[7.8]
 [7.8]
 [7.9]
 [7.9]
 [0. ]
 [0. ]]
[[7.84      ]
 [7.84      ]
 [7.84      ]
 [6.79333333]
 [6.79333333]
 [7.01111111]]
[[8.1]
 [8.1]
 [8.1]
 [8.2]
 [8.2]
 [8.2]]
[[7.5]
 [7.5]
 [7.5]
 [7.6]
 [7.5]
 [7.5]]
[[7.64      ]
 [7.64      ]
 [7.34666667]
 [7.34666667]
 [7.34666667]
 [0.        ]]
[[7.6]
 [7.6]
 [7.9]
 [7.9]
 [7.9]
 [0. ]]
[[7.9]
 [7.9]
 [7.9]
 [8. ]
 [8. ]
 [0. ]]
[[7.8]
 [7.8]
 [7.9]
 [7.9]
 [0. ]
 [0. ]]
[[7.7]
 [7.7]
 [7.7]
 [7.8]
 [7.8]
 [7.8]]
[[7.9]
 [7.9]
 [7.9]
 [7.9]
 [7.9]
 [7.9]]
[[7.3]
 [7.3]
 [7.6]
 [7.6]
 [7.6]
 [0. ]]
[[7.7]
 [7.7]
 [7.7]
 [7.7]
 [7.4]
 [7.7]]
[[7.1]
 [7.1]
 [7.1]
 [7.7]
 [7.7]
 [7.7]]
[[7.6]
 [7.6]
 [7.6]
 [7.6]
 [7.6]
 [7.6]]
[[6.7]
 [6.7]
 [6.7]
 [6.9]
 [6.8]
 [6.8]]
[[7.3]
 [7.3]
 [7.3]
 [6.9]
 [6.9]
 [6.9]]
[[7.5]
 [7.5]
 [7.5]
 [7.7]
 [7.7]
 [7.7]]
[[8.11]
 [8.11]
 [8.11]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.54365714]
 [7.54365714]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.06932727]
 [8.06932727]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.91945714]
 [7.91945714]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[8.12]
 [8.12]
 [8.16]
 [8.16]
 [0.  ]
 [0.  ]]
[[8.15332727]
 [8.15332727]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[7.44]
 [7.44]
 [7.45]
 [7.45]
 [7.45]
 [0.  ]]
[[6.  ]
 [6.  ]
 [7.44]
 [7.44]
 [0.  ]
 [0.  ]]
[[7.    ]
 [7.    ]
 [7.    ]
 [7.5374]
 [7.5374]
 [0.    ]]
[[7.594]
 [7.594]
 [7.594]
 [7.734]
 [7.734]
 [0.   ]]
[[7.594]
 [7.594]
 [7.594]
 [7.734]
 [7.734]
 [0.   ]]
[[7.304]
 [7.304]
 [7.304]
 [7.238]
 [7.238]
 [0.   ]]
[[7.8 ]
 [7.8 ]
 [7.8 ]
 [7.62]
 [7.62]
 [0.  ]]
[[8.02]
 [8.02]
 [8.02]
 [8.12]
 [8.12]
 [0.  ]]
[[7.826]
 [7.826]
 [7.826]
 [7.83 ]
 [7.83 ]
 [0.   ]]
[[7.22]
 [7.22]
 [7.22]
 [7.15]
 [7.15]
 [0.  ]]
[[7.48]
 [7.48]
 [7.48]
 [7.41]
 [7.41]
 [0.  ]]
[[8.04]
 [8.04]
 [8.07]
 [8.07]
 [0.  ]
 [0.  ]]
[[8.59]
 [8.59]
 [8.56]
 [8.56]
 [0.  ]
 [0.  ]]
[[8.65]
 [8.65]
 [8.67]
 [8.67]
 [0.  ]
 [0.  ]]
[[8.45]
 [8.45]
 [8.45]
 [8.45]
 [0.  ]
 [0.  ]]
[[8.34]
 [8.34]
 [8.35]
 [8.35]
 [0.  ]
 [0.  ]]
[[8.33]
 [8.33]
 [8.34]
 [8.34]
 [0.  ]
 [0.  ]]
[[8.37]
 [8.37]
 [8.16]
 [7.95]
 [7.95]
 [7.95]]
[[7.93]
 [7.93]
 [7.95]
 [7.92]
 [7.92]
 [0.  ]]
[[7.85]
 [7.85]
 [7.85]
 [7.98]
 [8.  ]
 [0.  ]]
[[8.02]
 [8.02]
 [8.01]
 [7.87]
 [7.87]
 [7.87]]
[[8.17  ]
 [8.17  ]
 [7.8172]
 [7.7288]
 [7.5286]
 [8.41  ]]
[[8.01  ]
 [8.01  ]
 [7.7972]
 [8.0454]
 [7.8382]
 [8.76  ]]
[[8.31]
 [8.31]
 [7.67]
 [7.84]
 [7.49]
 [7.5 ]]
[[8.    ]
 [8.    ]
 [8.1   ]
 [8.2494]
 [8.2494]
 [0.    ]]
[[8.3]
 [8.3]
 [8.2]
 [8.2]
 [8.2]
 [8.2]]
[[8.]
 [8.]
 [8.]
 [8.]
 [8.]
 [0.]]
[[8.2       ]
 [8.2       ]
 [8.        ]
 [7.03191758]
 [7.03191758]
 [0.        ]]
[[8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.3]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.4]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.4]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.6]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.5]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.8]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.9]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]
[[7.49]
 [7.49]
 [7.45]
 [7.45]
 [0.  ]
 [0.  ]]
[[8.5]
 [8.5]
 [8.5]
 [0. ]
 [0. ]
 [0. ]]
[[7.86]
 [7.86]
 [7.77]
 [7.77]
 [0.  ]
 [0.  ]]
[[7.94]
 [7.94]
 [8.03]
 [8.03]
 [0.  ]
 [0.  ]]
[[8.19]
 [8.19]
 [8.14]
 [8.14]
 [0.  ]
 [0.  ]]
[[8.05]
 [8.05]
 [8.05]
 [8.05]
 [0.  ]
 [0.  ]]
[[7.418]
 [7.418]
 [7.418]
 [0.   ]
 [0.   ]
 [0.   ]]
[[7.418]
 [7.418]
 [7.418]
 [0.   ]
 [0.   ]
 [0.   ]]
[[7.63]
 [7.63]
 [7.63]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.22]
 [8.22]
 [8.22]
 [8.22]
 [0.  ]
 [0.  ]]
[[8.16]
 [8.16]
 [8.16]
 [8.16]
 [0.  ]
 [0.  ]]
[[8.79]
 [8.79]
 [8.79]
 [8.79]
 [0.  ]
 [0.  ]]
[[7.83]
 [7.83]
 [7.83]
 [7.83]
 [0.  ]
 [0.  ]]
[[7.22]
 [7.22]
 [7.22]
 [7.56]
 [7.56]
 [0.  ]]
[[7.13]
 [7.13]
 [7.13]
 [7.12]
 [7.12]
 [0.  ]]
[[7.8]
 [7.8]
 [7.8]
 [7.8]
 [7.8]
 [0. ]]
[[7.18]
 [7.18]
 [7.18]
 [7.08]
 [7.08]
 [0.  ]]
[[7.6966]
 [7.6966]
 [7.6966]
 [0.    ]
 [0.    ]
 [0.    ]]
[[8.12]
 [8.12]
 [8.21]
 [8.6 ]
 [8.6 ]
 [8.6 ]]
[[8.29]
 [8.29]
 [8.36]
 [8.53]
 [8.57]
 [8.57]]
[[8.1]
 [8.1]
 [8.1]
 [0. ]
 [0. ]
 [0. ]]
[[8.2]
 [8.2]
 [8.2]
 [0. ]
 [0. ]
 [0. ]]
[[7.31]
 [7.31]
 [7.31]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.33]
 [7.33]
 [7.33]
 [0.  ]
 [0.  ]
 [0.  ]]
[[8.03]
 [8.03]
 [8.03]
 [0.  ]
 [0.  ]
 [0.  ]]
[[7.83]
 [7.83]
 [7.83]
 [7.83]
 [7.83]
 [0.  ]]
[[7.6 ]
 [7.6 ]
 [7.65]
 [7.91]
 [7.81]
 [0.  ]]
[[7.83]
 [7.83]
 [7.87]
 [7.83]
 [7.83]
 [0.  ]]
[[7.98]
 [7.98]
 [7.98]
 [7.99]
 [7.99]
 [7.99]]
[[7.89]
 [7.89]
 [7.89]
 [8.07]
 [8.  ]
 [8.  ]]
[[8.12]
 [8.12]
 [8.12]
 [8.12]
 [8.02]
 [0.  ]]
[[7.93]
 [7.93]
 [7.93]
 [7.93]
 [0.  ]
 [0.  ]]
[[8.32]
 [8.32]
 [8.32]
 [7.67]
 [7.67]
 [8.16]]
[[7.8 ]
 [7.8 ]
 [7.8 ]
 [8.15]
 [8.07]
 [8.16]]
[[8.4 ]
 [8.4 ]
 [8.11]
 [8.11]
 [8.09]
 [8.09]]
[[7.8 ]
 [7.8 ]
 [7.8 ]
 [8.15]
 [8.07]
 [8.16]]
[[7.934]
 [7.934]
 [8.11 ]
 [8.11 ]
 [8.09 ]
 [8.09 ]]
[[8.08]
 [8.08]
 [7.83]
 [7.83]
 [7.83]
 [7.53]]
[[7.8 ]
 [7.8 ]
 [7.8 ]
 [7.8 ]
 [7.74]
 [7.74]]
[[7.63]
 [7.63]
 [7.6 ]
 [7.6 ]
 [7.6 ]
 [7.6 ]]
[[7.918]
 [7.918]
 [0.   ]
 [0.   ]
 [0.   ]
 [0.   ]]
[[7.56 ]
 [7.56 ]
 [7.63 ]
 [7.63 ]
 [7.72 ]
 [7.942]]
[[7.66 ]
 [7.66 ]
 [7.8  ]
 [7.75 ]
 [7.604]
 [0.   ]]
[[7.93]
 [7.93]
 [7.79]
 [7.68]
 [7.81]
 [7.81]]
[[7.9 ]
 [7.9 ]
 [7.8 ]